<?php

/*
+-----------------------------------------------------------------------+
| language/et_EE/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['default_view'] = 'Vaikimisi vaade';
$labels['time_format'] = 'Ajavorming';
$labels['timeslots'] = 'Ajapilu tunni kohta';
$labels['duration'] = 'Sündmuse pikkus (vaikimisi)';
$labels['workdays'] = 'Tööpäevad';
$labels['first_day'] = 'Esimene nädalapäev';
$labels['categories'] = 'Kategooriad';
$labels['add_category'] = 'Lisa kategooria';
$labels['remove_category'] = 'Eemalda kategooria';
$labels['calendar_feeds'] = 'Kalendri vood';
$labels['add_feed'] = 'Lisa voog';
$labels['remove_feed'] = 'Eemalda voog';
$labels['cal_notify'] = 'Teata e-maili kaudu';
$labels['cal_notify_to'] = 'Saaja';
$labels['caltoken'] = 'Märk';
$labels['calconfidentialurl'] = 'Konfidentsiaalne voo ligipääs [%s]';
$labels['read_write'] = 'täielikud õigused (lugemine/kirjutamine)';
$labels['readonly'] = 'ainult lugemiseks';
$labels['calfeedurl'] = 'Voo URL';
$labels['feedaccesshint'] = 'Lõika ja kleebi ülevalolev URL ja jaga seda teiste %s kasutajatega jagamaks oma sündmusi (ainult lugemisõigusega) või kasutamaks läbi teiste voogusi toetavate programmide. Muuda või eemalda märk et sulgeda ligipääs.';
$labels['calendar'] = 'Kalender';
$labels['day'] = 'Päev';
$labels['workday'] = 'Tööpäev';
$labels['week'] = 'Nädal';
$labels['month'] = 'Kuu';
$labels['year'] = 'Aasta';
$labels['new_event'] = 'Uus sündmus';
$labels['edit_event'] = 'Redigeeri sündmust';
$labels['save'] = 'Salvesta';
$labels['remove'] = 'Eemalda';
$labels['cancel'] = 'Tühista';
$labels['summary'] = 'Kokkuvõte';
$labels['description'] = 'Kirjeldus';
$labels['all-day'] = 'kogu-päev';
$labels['export'] = 'Ekspordi ICS-i';
$labels['category'] = 'Kategooria';
$labels['location'] = 'Asukoht';
$labels['default'] = 'Puudub';
$labels['date'] = 'Kuupäev';
$labels['start'] = 'Start';
$labels['end'] = 'Lõpp';
$labels['recur'] = 'Korda sündmust';
$labels['recurs'] = 'Korda';
$labels['expires'] = 'Aegub';
$labels['never'] = 'mitte kunagi';
$labels['toggle_view'] = 'Vaheta vaadet';
$labels['generated'] = 'genereeritud:';
$labels['selectdate'] = 'Vali kuupäev';
$labels['prev_year'] = 'Eelmine aasta';
$labels['prev_month'] = 'Eelmine kuu';
$labels['next_year'] = 'Järgmine aasta';
$labels['next_month'] = 'Järgmine kuu';
$labels['choose_date'] = 'Vali kuupäev';
$labels['click_here'] = 'Klõpsa siia';
$labels['removed'] = 'Järgmine sündmus on eemaldatud!';
$labels['edited_by'] = 'Muudetud: ';
$labels['addicalmsg'] = 'Impordi kalendrisse';
$labels['icalsavefailed'] = 'Ei suutnud importide kalendrifaili';
$labels['importedsuccessfully'] = 'Edukalt imprditud';
$labels['switch_calendar'] = 'Vaheta kalendrit';
$labels['cal_user'] = 'Kalendri kasutaja';
$labels['submit'] = 'Sisesta';
$labels['filter_events'] = 'Filtreeri sündmuseid';
$labels['allevents'] = 'kõik sündmused';
$labels['removefilters'] = 'Eemalda filtrid';
$labels['defaultcategory'] = 'Vaikimisi';
$labels['undefined'] = '---';

?>
