<?php

/*
+-----------------------------------------------------------------------+
| language/nb_NO/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2010, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Dag Henning Liodden Sørbø                                     |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['default_view'] = 'Standard visning';
$labels['time_format'] = 'Tidsformat';
$labels['timeslots'] = 'Tidsenheter pr. time';
$labels['duration'] = 'Varighet til hendelse';
$labels['workdays'] = 'Arbeidsdager';
$labels['first_day'] = 'Første ukedag';
$labels['categories'] = 'Kategorier';
$labels['add_category'] = 'Legg til kategori';
$labels['remove_category'] = 'Fjern kategori';
$labels['calendar_feeds'] = 'Kalenderdelingskanal';
$labels['add_feed'] = 'Legg til kanal';
$labels['remove_feed'] = 'Fjern kanal';
$labels['cal_notify'] = 'Send påminnelse på e-post';
$labels['cal_notify_to'] = 'Mottaker';
$labels['caltoken'] = 'Kjennemerke';
$labels['calconfidentialurl'] = 'Konfidensiell kanaltilgang [%s]';
$labels['read_write'] = 'full tilgang (lese/skrive)';
$labels['readonly'] = 'skrivebeskyttet';
$labels['calfeedurl'] = 'Internettadresse til kanal';
$labels['feedaccesshint'] = 'Kopier internettadressen ovenfor og gi den til andre %s brukere for å dele dine hendelser i kalenderen eller få tilgang til hendelsene med et program som kan lese kanaler. Endre eller slett kjennemerket for å lukke tilgangen til kalenderen.';
$labels['calicsurl'] = 'ICS-adresse';
$labels['icsaccesshint'] = 'Bruk internettadressen ovenfor for å få tilgang til din kalender i Thunderbird eller andre programmer. Endre eller slett kjennemerket for å lukke tilgangen til kalenderen.';
$labels['calendar'] = 'Kalender';
$labels['day'] = 'Dag';
$labels['workday'] = 'Arbeidsdag';
$labels['week'] = 'Uke';
$labels['month'] = 'Måned';
$labels['year'] = 'År';
$labels['new_event'] = 'Ny hendelse';
$labels['edit_event'] = 'Endre hendelse';
$labels['save'] = 'Lagre';
$labels['remove'] = 'Fjern';
$labels['cancel'] = 'Avbryt';
$labels['summary'] = 'Sammendrag';
$labels['description'] = 'Beskrivelse';
$labels['all-day'] = 'hele dagen';
$labels['export'] = 'Eksporter til ICS';
$labels['category'] = 'Kategori';
$labels['location'] = 'Sted';
$labels['default'] = 'Ingen';
$labels['date'] = 'Dato';
$labels['start'] = 'Start';
$labels['end'] = 'Slutt';
$labels['recur'] = 'Gjenta hendelse hver';
$labels['recurs'] = 'Gjenta';
$labels['expires'] = 'Utløper';
$labels['never'] = 'aldri';
$labels['occurrences'] = 'Forekomster';
$labels['toggle_view'] = 'Bytt visning';
$labels['generated'] = 'generert den';
$labels['selectdate'] = 'Velg dato';
$labels['prev_year'] = 'Forrige år';
$labels['prev_month'] = 'Forrige måned';
$labels['next_year'] = 'Neste år';
$labels['next_month'] = 'Neste måned';
$labels['choose_date'] = 'Velge dato';
$labels['click_here'] = 'Klikk her';
$labels['removed'] = 'Følgende hendelse er fjernet!';
$labels['edited_by'] = 'Endret av';
$labels['addicalmsg'] = 'Importer inn i kalender';
$labels['icalsavefailed'] = 'Kunne ikke importere kalenderfil';
$labels['importedsuccessfully'] = 'Vellykket importering';
$labels['switch_calendar'] = 'Bytt kalender';
$labels['cal_user'] = 'Kalenderbruker';
$labels['submit'] = 'Bytt';
$labels['filter_events'] = 'Filtrer hendelser';
$labels['allevents'] = 'alle hendelser';
$labels['removefilters'] = 'Fjern filtre';
$labels['defaultcategory'] = 'Standard';
$labels['general'] = 'Generell';
$labels['schedule'] = 'Tidsplan';
$labels['every'] = 'Hver';
$labels['bydays'] = 'Velg dager';
$labels['byweekdays'] = 'Velg ukedager';
$labels['bymonthdays'] = 'Velg måneder';
$labels['advanced'] = 'Avansert';
$labels['first'] = 'første';
$labels['second'] = 'andre';
$labels['third'] = 'tredje';
$labels['fourth'] = 'fjerde';
$labels['fifth'] = 'femte';
$labels['last'] = 'siste';
$labels['january'] = 'Januar';
$labels['february'] = 'Februar';
$labels['march'] = 'Mars';
$labels['april'] = 'April';
$labels['may'] = 'Mai';
$labels['june'] = 'Juni';
$labels['july'] = 'Juli';
$labels['august'] = 'August';
$labels['september'] = 'September';
$labels['october'] = 'Oktober';
$labels['november'] = 'November';
$labels['december'] = 'Desember';
$labels['in'] = 'i';
$labels['export_as_file'] = 'Som fil';
$labels['send_invitation'] = 'Send invitasjon';
$labels['invitation_subject'] = 'Hendelsesinvitasjon';
$labels['upcoming'] = 'Hendelse starter om';
$labels['reminder_before'] = 'Send påminnelse før hendelsesstart';
$labels['undefined'] = '---';

?>