<?php

/*
+-----------------------------------------------------------------------+
| language/sv_SE/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['calendarprovider'] = 'Kalender';
$labels['forinstance'] = 't.ex.';
$labels['caldavserver'] = 'CalDAV Server';
$labels['caldavurl'] = 'CalDAV Url';
$labels['passwordisset'] = 'Lösenord är satt';
$labels['passwordisnotset'] = 'Lösenord är ej satt';
$labels['default_view'] = 'Standardvy';
$labels['timeslots'] = 'Markeringar per timme';
$labels['duration'] = 'Standardlängd på händelse (timmar)';
$labels['workdays'] = 'Arbetsdagar';
$labels['first_day'] = 'Första veckodag';
$labels['categories'] = 'Kategorier';
$labels['add_category'] = 'Lägg till kategori';
$labels['remove_category'] = 'Radera kategori';
$labels['calendar_feeds'] = 'Kalender feeds';
$labels['feeds'] = 'Kalender feeds';
$labels['add_feed'] = 'Lägg till feed';
$labels['remove_feed'] = 'Radera feed';
$labels['cal_notify'] = 'Skicka kopia till e-post';
$labels['cal_notify_to'] = 'Mottagare';
$labels['caltoken'] = 'Identifieringskod';
$labels['calconfidentialurl'] = 'Privat åtkomst till feed [%s]';
$labels['read_write'] = 'Full access (skriv/läs)';
$labels['readonly'] = 'Endast läs';
$labels['calfeedurl'] = 'Feed länk';
$labels['feedaccesshint'] = 'Kopiera och klistra in ovanstående webbadress och ge det till andra %s användare för att dela dina kalenderhändelser, eller gå in på webbadressen via en RSS-läsare. Ändra eller ta bort identifieringskod att stänga tillträde.';
$labels['calicsurl'] = 'ICS adress';
$labels['icsaccesshint'] = 'Använd ovanstående webbadress att komma åt din kalender genom Thunderbird eller andra klienter. Ändra eller ta bort identifieringskod att stänga tillträde.';
$labels['timeFormat'] = 'hh:mm';
$labels['titleFormatMonth'] = 'MMMM yyyy';
$labels['titleFormatDay'] = 'dddd';
$labels['columnFormatMonth'] = 'ddd';
$labels['columnFormatWeek'] = 'ddd';
$labels['columnFormatDay'] = 'dddd';
$labels['timeOnlyTitle'] = 'Välj tid';
$labels['timeText'] = 'Tid';
$labels['hourText'] = 'Timme';
$labels['minuteText'] = 'Minut';
$labels['currentText'] = 'Nu';
$labels['closeText'] = 'Klar';
$labels['calendar'] = 'Kalender';
$labels['yes'] = 'ja';
$labels['no'] = 'nej';
$labels['day'] = 'Dag';
$labels['workday'] = 'Arbetsdag';
$labels['week'] = 'Vecka';
$labels['calendar_week'] = 'Kalendervecka';
$labels['month'] = 'Månad';
$labels['year'] = 'År';
$labels['new_event'] = 'Ny händelse';
$labels['edit_event'] = 'Ändra händelse';
$labels['save'] = 'Spara';
$labels['remove'] = 'Radera';
$labels['cancel'] = 'Avbryt';
$labels['summary'] = 'Summering';
$labels['description'] = 'Beskrivning';
$labels['all-day'] = 'Hela dagen';
$labels['export'] = 'Exportera till ICS';
$labels['category'] = 'Kategori';
$labels['preview'] = 'Förhandsgranskning';
$labels['location'] = 'Plats';
$labels['default'] = 'Ingen';
$labels['date'] = 'Datum';
$labels['start'] = 'Start';
$labels['end'] = 'Slut';
$labels['recur'] = 'Repetera händelse varje';
$labels['recurs'] = 'Repetera';
$labels['expires'] = 'Löper ut';
$labels['infinite'] = 'oändlig';
$labels['reset'] = 'återställ';
$labels['never'] = 'aldrig';
$labels['occurrences'] = 'Förekomster';
$labels['toggle_view'] = 'Ändra vy';
$labels['generated'] = 'genererad';
$labels['selectdate'] = 'Välj datum';
$labels['prev_year'] = 'Föregående år';
$labels['prev_month'] = 'Föregående månad';
$labels['next_year'] = 'Nästa år';
$labels['next_month'] = 'Nästa månad';
$labels['choose_date'] = 'Välj datum';
$labels['click_here'] = 'Klicka här';
$labels['removed'] = 'Följande händelse har tagits bort!';
$labels['edited_by'] = 'Ändrad av';
$labels['addicalmsg'] = 'Importera till kalender';
$labels['icalsavefailed'] = 'Det gick inte att importera kalenderfilen';
$labels['importedsuccessfully'] = 'Importeringen slutförd';
$labels['switch_calendar'] = 'Byt kalender';
$labels['cal_user'] = 'Användare';
$labels['submit'] = 'Skicka';
$labels['filter_events'] = 'Filtrera händelser';
$labels['allevents'] = 'alla händelser';
$labels['removefilters'] = 'Ta bort filter';
$labels['defaultcategory'] = 'Standard';
$labels['general'] = 'Allmän';
$labels['schedule'] = 'Schemalägg';
$labels['every'] = 'Varje';
$labels['bydays'] = 'Per dag';
$labels['byweekdays'] = 'Per veckodagar';
$labels['bymonthdays'] = 'Per månad';
$labels['advanced'] = 'Avancerad';
$labels['first'] = 'första';
$labels['second'] = 'andra';
$labels['third'] = 'tredje';
$labels['fourth'] = 'fjärde';
$labels['fifth'] = 'femte';
$labels['last'] = 'sista';
$labels['january'] = 'Januari';
$labels['february'] = 'Februari';
$labels['march'] = 'Mars';
$labels['april'] = 'April';
$labels['may'] = 'Maj';
$labels['june'] = 'Juni';
$labels['july'] = 'Juli';
$labels['august'] = 'Augusti';
$labels['september'] = 'September';
$labels['october'] = 'Oktober';
$labels['november'] = 'November';
$labels['december'] = 'December';
$labels['in'] = 'i';
$labels['export_as_file'] = 'Som fil';
$labels['send_invitation'] = 'Skicka inbjudan';
$labels['invitation_subject'] = 'Eventinbjudan';
$labels['upcoming'] = 'Händelsen inträffar om';
$labels['reminder_before'] = 'Påminn innan händelsen inträffar';
$labels['show_upcoming_cal'] = 'Aktivera förhandsvisning för kommande händelser';
$labels['invalidresponse'] = 'Felaktigt svar från';
$labels['verifyexpiredate'] = 'Slutdatumet verkar osannolikt - vill du kontrollera det?';
$labels['recurwarning'] = 'Det här är en återkommande händelse.';
$labels['importconfirmation'] = 'Vill du importera bifogade händelser in i din kalender [%s st]?';
$labels['item'] = 'st';
$labels['run_tests'] = 'Testinställningar (nåbar endast för administratör)';
$labels['undefined'] = '---';

?>