<?php

/*
+-----------------------------------------------------------------------+
| language/tr_TR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['default_view'] = 'Varsayılan görünüm';
$labels['timeslots'] = 'Saat başına zaman aralığı';
$labels['duration'] = 'Etkinlik süresi (varsayılan)';
$labels['workdays'] = 'Çalışma Günleri';
$labels['first_day'] = 'Haftanın ilk günü';
$labels['categories'] = 'Kategoriler';
$labels['add_category'] = 'Kategori Ekle';
$labels['remove_category'] = 'Kategori Kaldır';
$labels['calendar_feeds'] = 'Takvim Kaynakları';
$labels['add_feed'] = 'Kaynak Ekle';
$labels['remove_feed'] = 'Kaynak Kaldır';
$labels['cal_notify'] = 'e-Posta ile uyar';
$labels['cal_notify_to'] = 'Alıcı';
$labels['caltoken'] = 'İşaret';
$labels['calconfidentialurl'] = 'Gizli besleme erişimi [%s]';
$labels['read_write'] = 'tam erişim (okuma/yazma)';
$labels['readonly'] = 'salt okunur';
$labels['calfeedurl'] = 'Kaynak URL';
$labels['feedaccesshint'] = 'Takviminizdeki etkinlikleri, aşağıdaki URL\'yi kopyala ve yapıştır ile diğer %s kullanıcılarıyla paylaşabilir veya bir Kaynak okuyucu ile URL erişimi yapabilirsiniz. İşareti değiştirerek veya kaldırarak erişimi kapatabilirsiniz.';
$labels['calicsurl'] = 'ICS URL';
$labels['icsaccesshint'] = 'Thunderbird veya başka Masaüstü istemcileri tarafından takviminize erişim için yukarıdaki URL\'yi kullanın. İşareti değiştirerek veya kaldırarak erişimi kapatabilirsiniz.';
$labels['timeFormat'] = 'HH:mm';
$labels['titleFormatMonth'] = 'MMMM yyyy';
$labels['titleFormatDay'] = 'dddd,';
$labels['columnFormatMonth'] = 'ddd';
$labels['columnFormatWeek'] = 'ddd';
$labels['columnFormatDay'] = 'dddd';
$labels['timeOnlyTitle'] = 'Zaman Seçin';
$labels['timeText'] = 'Zaman';
$labels['hourText'] = 'Saat';
$labels['minuteText'] = 'Dakika';
$labels['currentText'] = 'Şimdi';
$labels['closeText'] = 'Tamam';
$labels['calendar'] = 'Takvim';
$labels['yes'] = 'evet';
$labels['no'] = 'hayır';
$labels['day'] = 'Gün';
$labels['workday'] = 'Çalışma Günü';
$labels['week'] = 'Hafta';
$labels['calendar_week'] = 'Takvim ayı';
$labels['month'] = 'Ay';
$labels['year'] = 'Yıl';
$labels['new_event'] = 'Yeni etkinlik';
$labels['edit_event'] = 'Etkinliği düzenle';
$labels['save'] = 'Kaydet';
$labels['remove'] = 'Kaldır';
$labels['cancel'] = 'İptal';
$labels['summary'] = 'Özet';
$labels['description'] = 'Açıklama';
$labels['all-day'] = 'tüm-gün';
$labels['export'] = 'ICS Dışa Aktar';
$labels['category'] = 'Kategori';
$labels['preview'] = 'Ön izleme';
$labels['location'] = 'Konum';
$labels['default'] = 'Hiçbiri';
$labels['date'] = 'Tarih';
$labels['start'] = 'Başlangıç';
$labels['end'] = 'Bitiş';
$labels['recur'] = 'Etkinliği tekrarla';
$labels['recurs'] = 'Tekrarlama';
$labels['expires'] = 'Süre Bitimi';
$labels['infinite'] = 'sonsuz';
$labels['reset'] = 'sıfırla';
$labels['never'] = 'asla';
$labels['occurrences'] = 'Yineleme';
$labels['toggle_view'] = 'Geçiş görünümü';
$labels['generated'] = 'oluşturulur';
$labels['selectdate'] = 'Tarih seç';
$labels['prev_year'] = 'Önceki yıl';
$labels['prev_month'] = 'Önceki ay';
$labels['next_year'] = 'Gelecek yıl';
$labels['next_month'] = 'Gelecek ay';
$labels['choose_date'] = 'Tarih seçin';
$labels['click_here'] = 'Tıklayın';
$labels['removed'] = 'Aşağıdaki etkinlik kaldırıldı!';
$labels['edited_by'] = 'Takvim değiştirilmiş';
$labels['addicalmsg'] = 'Takvime aktar';
$labels['icalsavefailed'] = 'Takvim dosyası içe aktarılamadı';
$labels['importedsuccessfully'] = 'Başarıyla aktarıldı';
$labels['switch_calendar'] = 'Takvim değiştir';
$labels['cal_user'] = 'Takvim kullanıcısı';
$labels['submit'] = 'Gönder';
$labels['filter_events'] = 'Görevleri filtrele';
$labels['allevents'] = 'tüm görevler';
$labels['removefilters'] = 'Filtreleri Kaldır';
$labels['defaultcategory'] = 'Varsayılan';
$labels['general'] = 'Genel';
$labels['schedule'] = 'Tarife';
$labels['every'] = 'Her';
$labels['bydays'] = 'Gün olarak';
$labels['byweekdays'] = 'Hafta olarak';
$labels['bymonthdays'] = 'Ay olarak';
$labels['advanced'] = 'Gelişmiş';
$labels['first'] = 'birinci';
$labels['second'] = 'ikinci';
$labels['third'] = 'üçüncü';
$labels['fourth'] = 'dördüncü';
$labels['fifth'] = 'beşinci';
$labels['last'] = 'sonuncu';
$labels['january'] = 'Ocak';
$labels['february'] = 'Şubat';
$labels['march'] = 'Mart';
$labels['april'] = 'Nisan';
$labels['may'] = 'Mayıs';
$labels['june'] = 'Haziran';
$labels['july'] = 'Temmuz';
$labels['august'] = 'Ağustos';
$labels['september'] = 'Eylül';
$labels['october'] = 'Ekim';
$labels['november'] = 'Kasım';
$labels['december'] = 'Aralık';
$labels['in'] = 'içinde';
$labels['export_as_file'] = 'Dosya Olarak';
$labels['send_invitation'] = 'Davet Gönder';
$labels['invitation_subject'] = 'Etkinlik Daveti';
$labels['upcoming'] = 'Etkinlik başlar';
$labels['reminder_before'] = 'Etkinlik başlamadan önce hatırlat';
$labels['show_upcoming_cal'] = 'Yaklaşan etkinlik önizlemesini etkinleştir';
$labels['invalidresponse'] = 'Geçersiz yanıt';
$labels['verifyexpiredate'] = 'Süre bitim tarihi mantıksız. Kontrol etmek istermisiniz?';
$labels['recurwarning'] = 'Bu tekrar eden bir etkinlik.';
$labels['importconfirmation'] = 'Ekli etkinliği(leri) takviminize [%s item(s)] aktarmak istermisiniz?';
$labels['item'] = 'Öğe';
$labels['run_tests'] = 'Ayarları test et (sadece takvim yöneticisinin erişebilir)';
$labels['undefined'] = '---';

?>