<?php

/*
+-----------------------------------------------------------------------+
| language/uk_UA/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['default_view'] = 'Режим перегляду за замовчуванням';
$labels['timeslots'] = 'Інтервал часу в годині';
$labels['duration'] = 'Тривалість події (за замовчуванням)';
$labels['workdays'] = 'Робочі дні';
$labels['first_day'] = 'Перший день тижня';
$labels['categories'] = 'Категорії';
$labels['add_category'] = 'Додати категорію';
$labels['remove_category'] = 'Видалити категорію';
$labels['calendar_feeds'] = 'Календар RSS';
$labels['add_feed'] = 'Додати RSS';
$labels['remove_feed'] = 'Видалити RSS';
$labels['cal_notify'] = 'Повідомлення на email';
$labels['cal_notify_to'] = 'Одержувач';
$labels['caltoken'] = 'Маркер';
$labels['calconfidentialurl'] = 'Конфидеційний доступ до RSS [%s]';
$labels['read_write'] = 'повний доступ (читання/запис)';
$labels['readonly'] = 'тільки читання';
$labels['calfeedurl'] = 'URL RSS';
$labels['feedaccesshint'] = 'Скопіювати і вставити URL і передати його в іншим % S користувачам поділитися своїми подіями календаря або отримати доступ до URL шляхом читання RSS. Змінити або видалити маркер, щоб закрити доступ.';
$labels['calicsurl'] = 'ICS URL';
$labels['icsaccesshint'] = 'Використати URL для доступу до календаря з Thunderbird або інших Desktop-клієнтів. Змінити або видалити маркер, щоб закрити доступ.';
$labels['timeFormat'] = 'h:mmt';
$labels['titleFormatMonth'] = 'MMMM yyyy';
$labels['titleFormatDay'] = 'dddd,';
$labels['columnFormatMonth'] = 'ddd';
$labels['columnFormatWeek'] = 'ddd';
$labels['columnFormatDay'] = 'dddd';
$labels['timeOnlyTitle'] = 'Оберіть час';
$labels['timeText'] = 'Час';
$labels['hourText'] = 'Година';
$labels['minuteText'] = 'Хвилина';
$labels['currentText'] = 'Зараз';
$labels['closeText'] = 'Готово';
$labels['calendar'] = 'Календар';
$labels['yes'] = 'так';
$labels['no'] = 'ні';
$labels['day'] = 'День';
$labels['workday'] = 'Робочий день';
$labels['week'] = 'Тиждень';
$labels['calendar_week'] = 'Календар на тиждень';
$labels['month'] = 'Місяць';
$labels['year'] = 'Рік';
$labels['new_event'] = 'Нова подія';
$labels['edit_event'] = 'Редагувати подію';
$labels['save'] = 'Зберегти';
$labels['remove'] = 'Видалити';
$labels['cancel'] = 'Відмінити';
$labels['summary'] = 'Додати';
$labels['description'] = 'Опис';
$labels['all-day'] = 'всі дні';
$labels['export'] = 'Експортувати до ICS';
$labels['category'] = 'Категорія';
$labels['preview'] = 'Попередній перегляд';
$labels['location'] = 'Розташування';
$labels['default'] = 'Відсутній';
$labels['date'] = 'Дата';
$labels['start'] = 'Початок';
$labels['end'] = 'Кінець';
$labels['recur'] = 'Повторити кожну подію';
$labels['recurs'] = 'Повторити';
$labels['expires'] = 'Прострочено';
$labels['infinite'] = 'нескінченно';
$labels['reset'] = 'скинути';
$labels['never'] = 'ніколи';
$labels['toggle_view'] = 'Змінити вигляд';
$labels['generated'] = 'створених у ';
$labels['selectdate'] = 'Вибір дати';
$labels['prev_year'] = 'Попередній рік';
$labels['prev_month'] = 'Попередній місяць';
$labels['next_year'] = 'Наступний рік';
$labels['next_month'] = 'Наступний місяць';
$labels['choose_date'] = 'Обрати дату';
$labels['click_here'] = 'Натисніть тут';
$labels['removed'] = 'Наступну подію було видалено!';
$labels['edited_by'] = 'Календар було змінено';
$labels['addicalmsg'] = 'Імпортувати до календаря';
$labels['icalsavefailed'] = 'Неможливо імпортувати файл календаря';
$labels['importedsuccessfully'] = 'Все імпортовано';
$labels['switch_calendar'] = 'Перемикач календаря';
$labels['cal_user'] = 'Користувач календаря';
$labels['submit'] = 'Надіслати';
$labels['filter_events'] = 'Фільтр подій';
$labels['allevents'] = 'всі події';
$labels['removefilters'] = 'Видалити фільтри';
$labels['defaultcategory'] = 'За замовчуванням';
$labels['general'] = 'Головна';
$labels['schedule'] = 'Планування';
$labels['every'] = 'Кожен';
$labels['bydays'] = 'По днях';
$labels['byweekdays'] = 'По робочих днях';
$labels['bymonthdays'] = 'По місяцях';
$labels['advanced'] = 'Розширений';
$labels['first'] = 'перший';
$labels['second'] = 'другий';
$labels['third'] = 'третій';
$labels['fourth'] = 'четвертий';
$labels['fifth'] = 'п’ятий';
$labels['last'] = 'останній';
$labels['january'] = 'Січень';
$labels['february'] = 'Лютий';
$labels['march'] = 'Березень';
$labels['april'] = 'Квітень';
$labels['may'] = 'Травень';
$labels['june'] = 'Червень';
$labels['july'] = 'Липень';
$labels['august'] = 'Серпень';
$labels['september'] = 'Вересень';
$labels['october'] = 'Жовтень';
$labels['november'] = 'Листопад';
$labels['december'] = 'Грудень';
$labels['in'] = 'в';
$labels['export_as_file'] = 'До файлу';
$labels['send_invitation'] = 'Надіслати повідомлення';
$labels['invitation_subject'] = 'Повідомлення про подію';
$labels['upcoming'] = 'Подія почнеться о';
$labels['reminder_before'] = 'Нагадати про початок події';
$labels['show_upcoming_cal'] = 'Включити перегляд майбутніх подій';
$labels['invalidresponse'] = 'Невірна відповідь від';
$labels['verifyexpiredate'] = 'Дата закінчення терміну неправдоподібна. Ви хочете перевірити це?';
$labels['recurwarning'] = 'Це циклічна подія.';
$labels['importconfirmation'] = 'Ви хочете імпортувати вкладені подія (ї) у ваш календар [% S пункт (ів)]?';
$labels['item'] = 'Пункт';
$labels['run_tests'] = 'Протестувати налаштування (доступно тільки для адміністратора календаря)';
$labels['undefined'] = '---';

?>