<?php

/*
+-----------------------------------------------------------------------+
| language/zh_CN/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:  Jeff Tan                                                  |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['default_view'] = '预设View';
$labels['time_format'] = '时间格式';
$labels['timeslots'] = '每小时时间格数目';
$labels['duration'] = '预设时间长度';
$labels['workdays'] = '工作天';
$labels['first_day'] = '每周的第一天';
$labels['categories'] = '分类';
$labels['add_category'] = '新增分类';
$labels['remove_category'] = '移除分类';
$labels['calendar_feeds'] = '日历派送';
$labels['feeds'] = '日历派送';
$labels['add_feed'] = '增加派送';
$labels['remove_feed'] = '移除派送';
$labels['cal_notify'] = '使用邮件通知';
$labels['cal_notify_to'] = '接收者';
$labels['caltoken'] = '标记';
$labels['calconfidentialurl'] = '存取信任派送 [%s]';
$labels['read_write'] = '完全存取(读/写)';
$labels['readonly'] = '只读';
$labels['calfeedurl'] = '派送URL';
$labels['feedaccesshint'] = '复制然后粘贴上述URL，然后发送给其他用户 %s 以分享你的日历行程，或者通过派送读取器存取URL链接。修改或删除标记可以关闭存取';
$labels['calicsurl'] = 'ICS URL';
$labels['icsaccesshint'] = '在Thunderbird或其他桌面客户端使用上述URL连接可存取你的日历行程。如要關閉存取，修改或删除标记可以关闭存取';
$labels['calendar'] = '日历';
$labels['day'] = '日';
$labels['workday'] = '工作天';
$labels['week'] = '周';
$labels['month'] = '月';
$labels['year'] = '年';
$labels['new_event'] = '新事件';
$labels['edit_event'] = '编辑事件';
$labels['save'] = '保存';
$labels['remove'] = '移除';
$labels['cancel'] = '取消';
$labels['summary'] = '摘要';
$labels['description'] = '描述';
$labels['all-day'] = '整天';
$labels['export'] = '导出成ICS';
$labels['category'] = '分类';
$labels['location'] = '地点';
$labels['default'] = '无';
$labels['date'] = '日期';
$labels['start'] = '开始';
$labels['end'] = '结束';
$labels['recur'] = '事件重复每';
$labels['recurs'] = '重复';
$labels['expires'] = '期限';
$labels['never'] = '没有';
$labels['occurrences'] = '记录';
$labels['toggle_view'] = '切换View';
$labels['generated'] = '生成在';
$labels['selectdate'] = '选择日期';
$labels['prev_year'] = '前一年';
$labels['prev_month'] = '前一个月';
$labels['next_year'] = '下一年';
$labels['next_month'] = '下一个月';
$labels['choose_date'] = '选择日期';
$labels['click_here'] = '点这里';
$labels['removed'] = '以下事件已经被移除';
$labels['edited_by'] = '修改由';
$labels['addicalmsg'] = '导入行事曆';
$labels['icalsavefailed'] = '无法导入行事曆档案';
$labels['importedsuccessfully'] = '成功导入';
$labels['switch_calendar'] = '切换日历';
$labels['cal_user'] = '日历使用者';
$labels['submit'] = '提交';
$labels['filter_events'] = '过滤事件';
$labels['allevents'] = '所有事件';
$labels['removefilters'] = '移除过滤';
$labels['defaultcategory'] = '预设';
$labels['general'] = '一般';
$labels['schedule'] = '行程';
$labels['every'] = '每';
$labels['bydays'] = '按 天';
$labels['byweekdays'] = '按 周';
$labels['bymonthdays'] = '按 月';
$labels['advanced'] = '高级选项';
$labels['first'] = '第一';
$labels['second'] = '第二';
$labels['third'] = '第三';
$labels['fourth'] = '第四';
$labels['fifth'] = '第五';
$labels['last'] = '最后';
$labels['january'] = '一月';
$labels['february'] = '二月';
$labels['march'] = '三月';
$labels['april'] = '四月';
$labels['may'] = '五月';
$labels['june'] = '六月';
$labels['july'] = '七月';
$labels['august'] = '八月';
$labels['september'] = '九月';
$labels['october'] = '十月';
$labels['november'] = '十一月';
$labels['december'] = '十二月';
$labels['in'] = '在';
$labels['export_as_file'] = '导出成文档';
$labels['send_invitation'] = '传送邀请';
$labels['invitation_subject'] = '事件邀请';
$labels['undefined'] = '---';
$labels['mycalendar'] = '我的日历';
$labels['allcalendars'] = '全部日历';
$labels['calendar_week'] = '日历周';
$labels['reminders'] = '提醒';
$labels['reminder'] = '提醒';
$labels['infinite'] = '无限期';
$labels['reset'] = '重置';
$labels['externalreminders'] = '外部提醒服务 (f.e. Google Calendar)';
$labels['remindertype'] = '提醒方式';
$labels['email'] = 'Email';
$labels['popup'] = 'Popup';
$labels['minutesbefore'] = '提前分钟数';
$labels['hoursbefore'] = '提前小时数';
$labels['daysbefore'] = '提前天数';
$labels['weeksbefore'] = '提前周数';
$labels['mailto'] = 'Mail至';
$labels['other'] = '其它';
$labels['reminderenable'] = '启用提醒';
$labels['reminderdisable'] = '禁用提醒';
$labels['customreminder'] = '用户自定义';
/* jquery-ui timepicker addon */
$labels['timeOnlyTitle'] = '选择时间';
$labels['timeText'] = '时间';
$labels['hourText'] = '时(H)';
$labels['minuteText'] = '分(m)';
$labels['currentText'] = '现时';
$labels['closeText'] = '完成';
?>