<?php

/*
+-----------------------------------------------------------------------+
| language/zh_TW/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:  ysliuthomas                                                  |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['default_view'] = '預設View';
$labels['time_format'] = '時間格式';
$labels['timeslots'] = '每小時時間格數目';
$labels['duration'] = '預設時間長度';
$labels['workdays'] = '工作天';
$labels['first_day'] = '每週的第一天';
$labels['categories'] = '分類';
$labels['add_category'] = '新增分類';
$labels['remove_category'] = '移除分類';
$labels['calendar_feeds'] = '行事曆Feed';
$labels['add_feed'] = '增加Feed';
$labels['remove_feed'] = '移除Feed';
$labels['cal_notify'] = '使用郵件通知';
$labels['cal_notify_to'] = '接收者';
$labels['caltoken'] = '記號';
$labels['calconfidentialurl'] = '私人Feed存取 [%s]';
$labels['read_write'] = '完全存取(讀/寫)';
$labels['readonly'] = '只能讀取';
$labels['calfeedurl'] = 'Feed URL';
$labels['feedaccesshint'] = '複製然後貼上上述URL，之後傳給其他使用者 %s 來分享你的行事曆事件或由Feed讀取器 存取URL。如要關閉存取，請修改或移除代號';
$labels['calicsurl'] = 'ICS URL';
$labels['icsaccesshint'] = '從Thunderbird或其他桌面客戶端，使用上述URL去存取你的行事曆。如要關閉存取，請修改或移除代號';
$labels['calendar'] = '行事曆';
$labels['day'] = '日';
$labels['workday'] = '工作天';
$labels['week'] = '周';
$labels['month'] = '月';
$labels['year'] = '年';
$labels['new_event'] = '新事件';
$labels['edit_event'] = '編輯事件';
$labels['save'] = '儲存';
$labels['remove'] = '移除';
$labels['cancel'] = '取消';
$labels['summary'] = '摘要';
$labels['description'] = '描述';
$labels['all-day'] = '整天';
$labels['export'] = '匯出成ICS';
$labels['category'] = '分類';
$labels['location'] = '地點';
$labels['default'] = '無';
$labels['date'] = '日期';
$labels['start'] = '開始';
$labels['end'] = '結束';
$labels['recur'] = '事件重複每';
$labels['recurs'] = '重複';
$labels['expires'] = '期限';
$labels['never'] = '沒有';
$labels['occurrences'] = '紀錄';
$labels['toggle_view'] = '切換View';
$labels['generated'] = '生成在';
$labels['selectdate'] = '選擇日期';
$labels['prev_year'] = '前一年';
$labels['prev_month'] = '前一個月';
$labels['next_year'] = '下一年';
$labels['next_month'] = '下一個月';
$labels['choose_date'] = '選擇日期';
$labels['click_here'] = '點這裡';
$labels['removed'] = '以下事件已經被移除';
$labels['edited_by'] = '修改由';
$labels['addicalmsg'] = '匯入行事曆';
$labels['icalsavefailed'] = '無法匯入行事曆檔案';
$labels['importedsuccessfully'] = '成功匯入';
$labels['switch_calendar'] = '切換行事曆';
$labels['cal_user'] = '行事曆使用者';
$labels['submit'] = '提交';
$labels['filter_events'] = '過濾事件';
$labels['allevents'] = '所有事件';
$labels['removefilters'] = '移除過濾';
$labels['defaultcategory'] = '預設';
$labels['general'] = '一般';
$labels['schedule'] = '行程';
$labels['every'] = '每';
$labels['bydays'] = '依照 天';
$labels['byweekdays'] = '依照 月';
$labels['bymonthdays'] = '依照 年';
$labels['advanced'] = '進階';
$labels['first'] = '第一';
$labels['second'] = '第二';
$labels['third'] = '第三';
$labels['fourth'] = '第四';
$labels['fifth'] = '第五';
$labels['last'] = '最後';
$labels['january'] = '一月';
$labels['february'] = '二月';
$labels['march'] = '三月';
$labels['april'] = '四月';
$labels['may'] = '五月';
$labels['june'] = '六月';
$labels['july'] = '七月';
$labels['august'] = '八月';
$labels['september'] = '九月';
$labels['october'] = '十月';
$labels['november'] = '十一月';
$labels['december'] = '十二月';
$labels['in'] = '在';
$labels['export_as_file'] = '匯出成檔案';
$labels['send_invitation'] = '傳送邀請';
$labels['invitation_subject'] = '事件邀請';
$labels['undefined'] = '---';

?>