<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/en_US.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 11/27/2012 16:23:01
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Manage your contacts on CardDAV servers.';
$labels['settings'] = 'CardDAV Settings';
$labels['sharing'] = 'Sharing';
$labels['share'] = 'Share';
$labels['resource'] = 'Resource';
$labels['confidentialcarddavaccess'] = 'Confidential CardDAV access [%s]';
$labels['sharehint'] = 'Provide the above information (Username, Password (Token) and URLs) for  others to connect to your shared addressbooks.<br />This information grants read and write access. Change or remove the token to close access.';
$labels['sharehint_readonly'] = 'Provide the above information (Username, Password (Token) and URLs) for  others to connect to your shared addressbooks.<br />This information grants read-only access. Change or remove the token to close access.';
$labels['readwrite'] = 'read/write';
$labels['readonly'] = 'read only';
$labels['abooktoken'] = 'Token';
$labels['isenabled'] = 'is enabled';
$labels['isdisabled'] = 'is disabled';
$labels['sync_short'] = 'Synchronize';
$labels['sync'] = 'Synchronize CardDAVs';
$labels['add'] = 'Add';
$labels['server_url'] = 'CardDAV Server URL';
$labels['settings_label'] = 'Category';
$labels['settings_read_only'] = 'Read only';
$labels['settings_curl_not_installed'] = 'The PHP extension CURL is not installed! Please install CURL to use the CardDAV plugin.';
$labels['addressbook_contacts'] = 'CardDAV contacts';
$labels['settings_empty_values'] = 'Please fill out all Label and URL';
$labels['settings_saved'] = 'CardDAV server settings and vCards saved';
$labels['settings_save_failed'] = 'Failed to save CardDAV server settings';
$labels['settings_delete_loading'] = 'Delete CardDAV server settings and related contacts';
$labels['settings_delete_warning'] = 'Are you sure? If you proceed all contacts in this addressbook will be deleted permanently. This action can\'t be reverted!';
$labels['settings_deleted'] = 'CardDAV server settings deleted';
$labels['settings_delete_failed'] = 'Failed to delete CardDAV server settings';
$labels['settings_no_connection'] = 'Can\'t connect to the CardDAV server';
$labels['settings_init_server'] = 'Checking CardDAV server connection and import vCards';
$labels['addressbook_synced'] = 'CardDAV contacts synchronized';
$labels['addressbook_sync_failed'] = 'An error occurred while synchronizing the CardDAV contacts';
$labels['addressbook_sync_loading'] = 'Synchronize CardDAV contacts';
$labels['contact_moved_single'] = 'contact successfully moved';
$labels['contact_moved_multiple'] = 'contacts successfully moved';
$labels['autocomplete'] = 'Auto­complete';
$labels['automaticallycollected'] = 'Automatically Collected';
$labels['automaticallycollected_local'] = 'Automatically Collected (local)';
$labels['useautoabook'] = 'Use automatic address book';
$labels['useforcompletion'] = 'Use automatically collected addresses for autocompletion';
$labels['automatic_addressbook'] = 'Add automatically collected contacts to...';
$labels['googlecontacts'] = 'Google Contacts';
$labels['usegoogleabook'] = 'Use Google addressbook';
$labels['googleuser'] = 'Google Account';
$labels['googlepass'] = 'Google Password';
$labels['googlepassisset'] = 'Google Password is been entered';
$labels['googlepassisnotset'] = 'No Google Password entered yet';
$labels['toggle'] = 'toggle';
$labels['protected'] = 'protected';
$labels['defaultaddressbook'] = 'Personal Contacts';
$labels['Google'] = 'Google';
$labels['Global'] = 'Global (readonly)';
$labels['Work'] = 'Work';
$labels['Family'] = 'Family';
$labels['Personal'] = 'Personal';
$labels['Collected'] = 'Collected';
$labels['local'] = 'local';
$labels['fe'] = 'f.e.';
$labels['googlecaptcha'] = 'Grant access to your Google Account';
$labels['clickhere'] = 'Click here';
$labels['blank'] = ' ';

?>