<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/23/2013 08:42:56
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Administrar contactos en servidores CardDAV.';
$labels['settings'] = 'Configuración CardDAV';
$labels['sharing'] = 'Compartir';
$labels['share'] = 'Compartir';
$labels['resource'] = 'Recurso';
$labels['confidentialcarddavaccess'] = 'Acceso CardDAV confidencial';
$labels['sharehint'] = 'Proporcione la información anterior (Nombre de usuario, Contraseña (Token) y URLs) para que otros puedan conectarse a sus libretas de direcciones. Esta información concede permisos de lectura y escritura. Cambie o elimine el token para cerrar el acceso.';
$labels['sharehint_readonly'] = 'Proporcione la información anterior (Nombre de usuario, Contraseña (Token) y URLs) para que otros puedan conectarse a sus sus libretas de direcciones. <br />Esta información concede permisos de sólo lectura. Cambie o elimine el token para cerrar el acceso.';
$labels['readwrite'] = 'lectura/escritura';
$labels['readonly'] = 'sólo lectura';
$labels['abooktoken'] = 'Token';
$labels['isenabled'] = 'está habilitado';
$labels['isdisabled'] = 'está deshabilitado';
$labels['sync_short'] = 'Sincronizar';
$labels['sync'] = 'Sincronizar CardDAVs';
$labels['add'] = 'Añadir';
$labels['server_url'] = 'URL del servidor CardDAV';
$labels['settings_label'] = 'Categoría';
$labels['settings_read_only'] = 'Solo lectura';
$labels['settings_curl_not_installed'] = 'La extensión CURL de PHP no está instalada! Por favor, instale y habilite CURL para usar el complemento CardDAV.';
$labels['addressbook_contacts'] = 'Contactos CardDAV';
$labels['settings_empty_values'] = 'Por favor complete todos los campos y URL';
$labels['settings_saved'] = 'Configuración del servidor CardDAV y vCards guardados';
$labels['settings_save_failed'] = 'No se pudo guardar la configuración del servidor CardDAV';
$labels['settings_delete_loading'] = 'Eliminar la configuración del servidor CardDAV y los contactos locales relacionados';
$labels['settings_deleted'] = 'Configuración de servidor CardDAV eliminada';
$labels['settings_delete_failed'] = 'No se pudo eliminar la configuración del servidor CardDAV';
$labels['settings_no_connection'] = 'No se puede conectar al servidor CardDAV';
$labels['settings_init_server'] = 'Comprobando conexión al servidor CardDAV e importando vCards ';
$labels['addressbook_synced'] = 'Contactos CardDAV sincronizados';
$labels['addressbook_sync_failed'] = 'Se produjo un error al sincronizar los contactos CardDAV';
$labels['addressbook_sync_loading'] = 'Sincronizar contactos CardDAV';
$labels['contact_moved_single'] = 'contacto movido éxitosamente';
$labels['contact_moved_multiple'] = 'contactos movido éxitosamente';
$labels['autocomplete'] = 'Autocompletar';
$labels['automaticallycollected'] = 'Direcciones recientes';
$labels['automaticallycollected_local'] = 'Colectados automáticamente (local';
$labels['useautoabook'] = 'Utilizar la libreta de direcciones automática';
$labels['useforcompletion'] = 'Usar las direcciones automáticamente colectadas para autocompletado';
$labels['automatic_addressbook'] = 'Agregar contactos automáticamente colectados a...';
$labels['googlecontacts'] = 'Contactos de Google';
$labels['usegoogleabook'] = 'Utilizar libreta de direcciones de Google ';
$labels['googleuser'] = 'Cuenta de Google';
$labels['googlepass'] = 'Contraseña de Google';
$labels['googlepassisset'] = 'Contraseña de Google está presente';
$labels['googlepassisnotset'] = 'Introducir Contraseña de Google';
$labels['toggle'] = 'expandir';
$labels['protected'] = 'protegido';
$labels['defaultaddressbook'] = 'Contactos Personales';
$labels['Google'] = 'Google';
$labels['Global'] = 'Global (solo lectura)';
$labels['Work'] = 'Trabajo';
$labels['Family'] = 'Familiar';
$labels['Personal'] = 'Personal';
$labels['Collected'] = 'Colectados';
$labels['local'] = 'local';
$labels['fe'] = 'p.e.';
$labels['googlecaptcha'] = 'Permitir acceso a tu cuenta de Google';
$labels['clickhere'] = 'Haga clic aquí';
$labels['submenuprefix'] = '» ';
$labels['blank'] = ' ';

?>