<?php

/*
+-----------------------------------------------------------------------+
| language/et_EE/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['automaticallycollected'] = 'Automaatselt korjatud';
$labels['useautoabook'] = 'Kasuta automaatset aadresside korjamist';

?>
