<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Thomas Parvais - 06/17/2013 11:12:29
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Gêrer vos contacts sur un serveur CardDAV';
$labels['settings'] = 'Paramètres CardDAV';
$labels['sharing'] = 'Partager';
$labels['share'] = 'Partage';
$labels['resource'] = 'Ressource';
$labels['confidentialcarddavaccess'] = 'Accès CardDAV confidentiel [%s]';
$labels['sharehint'] = 'Veuillez fournir les informations demandées ce-dessus (login, mot de passe (jeton) et URLs) pour que les autres utilisateurs puissent se accéder à votre carnet d\'adresses partagé. Accès en écriture et lecture. Changer ou supprimer le mot de passe (jeton) pour fermer l\'accès';
$labels['sharehint_readonly'] = 'Veuillez fournir les informations demandées ce-dessus (login, mot de passe (jeton) et URLs) pour que les autres utilisateurs puissent se accéder à votre carnet d\'adresses partagé. Accès en lecture uniquement. Changer ou supprimer le mot de passe (jeton) pour fermer l\'accès';
$labels['readwrite'] = 'lecture/écriture';
$labels['readonly'] = 'lecture seule';
$labels['abooktoken'] = 'Jeton';
$labels['isenabled'] = 'est activé';
$labels['isdisabled'] = 'est désactivé';
$labels['sync_short'] = 'Synchroniser';
$labels['sync'] = 'Synchroniser les CardDAVs';
$labels['add'] = 'ajouter';
$labels['server_url'] = 'URL du serveur CardDAV';
$labels['settings_label'] = 'Catégorie';
$labels['settings_read_only'] = 'Lecture seule';
$labels['settings_curl_not_installed'] = 'L\'extension PHP CURL n\'est pas installée ! Veuillez l\'installer avant d\'utiliser CardDAV';
$labels['addressbook_contacts'] = 'Contacts CardDAV';
$labels['settings_empty_values'] = 'Veuillez remplir tous les champs et l\'URL';
$labels['settings_saved'] = 'Les paramètres CardDAV et les vCards sauvegardées';
$labels['settings_save_failed'] = 'Echec lors de la sauvegarde des paramètres de configuration CardDAV';
$labels['settings_delete_loading'] = 'Effacer les paramètres de configuration CardDAV et les contacts (local)';
$labels['settings_deleted'] = 'Paramètres de configuration CardDAV effacés';
$labels['settings_delete_failed'] = 'Echec lors de l\'effacement des paramètres de configuration CardDAV';
$labels['settings_no_connection'] = 'Impossible de se connecter au service CardDAV';
$labels['settings_init_server'] = 'Vérificationde la connexion au serveur CardDAV et imporation des vCards';
$labels['addressbook_synced'] = 'Contacts CardDAV synchronisés';
$labels['addressbook_sync_failed'] = 'Erreur lors de la synchronisation des contacts CardDAV';
$labels['addressbook_sync_loading'] = 'Synchroniser les CardDAV contacts';
$labels['contact_moved_single'] = 'Le contact a été déplacé';
$labels['contact_moved_multiple'] = 'Les contacts ont été déplacés';
$labels['autocomplete'] = 'Autocomplete';
$labels['automaticallycollected'] = 'Collectées automatiquement';
$labels['automaticallycollected_local'] = 'Adresse automatiquement collectée (local)';
$labels['useautoabook'] = 'Utiliser le carnet d\'adresses automatique';
$labels['useforcompletion'] = 'Utiliser les adresses collectées automatiquement pour l\'autocomplétion';
$labels['automatic_addressbook'] = 'Ajouter automatiquement les contacts collectés à...';
$labels['toggle'] = '(Dés)activer';
$labels['protected'] = 'Protégé';
$labels['defaultaddressbook'] = 'Contacts personnels';
$labels['Global'] = 'Global (lecture)';
$labels['Work'] = 'Travail';
$labels['Family'] = 'Famille';
$labels['Personal'] = 'Personnel';
$labels['Collected'] = 'Collecté';
$labels['local'] = 'local';
$labels['submenuprefix'] = '>>';
$labels['blank'] = 'vide';

?>