<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/it_IT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Roberto - 11/06/2012 09:55:38
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Gestisci i tuoi contatti su un server CardDAV';
$labels['settings'] = 'Impostazioni CardDAV';
$labels['sync_short'] = 'Sincronizza';
$labels['sync'] = 'Sincronizza tutto';
$labels['add'] = 'Aggiungi';
$labels['server_url'] = 'URL del server CardDAV';
$labels['settings_label'] = 'Categoria';
$labels['settings_read_only'] = 'Sola lettura';
$labels['settings_curl_not_installed'] = 'L\'estensione PHP CURL non è installata! Per utilizzare il plugin CardDAV sei pregato di installarla.';
$labels['addressbook_contacts'] = 'Contatti CardDAV';
$labels['settings_empty_values'] = 'Per favore, completa tutti i campi e gli URL';
$labels['settings_saved'] = 'Impostazioni server CardDAV e vCards salvate';
$labels['settings_save_failed'] = 'Non è stato possibile salvare le impostazioni CardDAV';
$labels['settings_delete_loading'] = 'Cancella il server CardDAV e i relativi contatti locali';
$labels['settings_deleted'] = 'Impostazioni server CardDAV eliminate';
$labels['settings_delete_failed'] = 'Non è stato possibile eliminare le impostazioni del server CardDAV';
$labels['settings_no_connection'] = 'Non è possibile contattare il server CardDAV';
$labels['settings_init_server'] = 'Controllo connessione al server CardDAV e importazione vCards';
$labels['addressbook_synced'] = 'Contatti CardDAV sincronizzati';
$labels['addressbook_sync_failed'] = 'Si è verificato un errore durante la sincronizzazione dei contatti CardDAV';
$labels['addressbook_sync_loading'] = 'Sincronizza contatti CardDAV';
$labels['contact_moved_single'] = 'Contatto spostato con successo';
$labels['contact_moved_multiple'] = 'Contatti spostati con successo';
$labels['autocomplete'] = 'Completamento automatico';
$labels['automaticallycollected'] = 'Raccolti automaticamente';
$labels['automaticallycollected_local'] = 'Raccolti automaticamente (locale)';
$labels['useautoabook'] = 'Usa rubrica automatica';
$labels['useforcompletion'] = 'Usa indirizzi raccolti automaticamente per l\'autocompletamento';
$labels['automatic_addressbook'] = 'Aggiungi contatti importati automaticamente a...';
$labels['googlecontacts'] = 'Contatti Google';
$labels['usegoogleabook'] = 'Usa agenda Google';
$labels['googleuser'] = 'Account Google';
$labels['googlepass'] = 'Password di accesso all\'account Google';
$labels['googlepassisset'] = 'Password Google impostata';
$labels['googlepassisnotset'] = 'Password Google non impostata';
$labels['toggle'] = 'Attivato';
$labels['protected'] = 'Protetto';
$labels['defaultaddressbook'] = 'Contatti personali';
$labels['Google'] = 'Google';
$labels['Global'] = 'Generica (locale)';
$labels['Work'] = 'Lavoro';
$labels['Family'] = 'Famiglia';
$labels['Personal'] = 'Personale';
$labels['Collected'] = 'Importati';
$labels['local'] = 'locale';
$labels['fe'] = 'f.e.';
$labels['googlecaptcha'] = 'Consenti l\'accesso al tuo account Google';
$labels['clickhere'] = 'Clicca qui';
$labels['blank'] = '  ';

?>