<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/nl_NL.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Emiel Wieldraaijer - 12/15/2012 15:26:12
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Beheer uw contacten op CardDAV servers';
$labels['settings'] = 'CardDAV instellingen';
$labels['sync_short'] = 'Synchroniseren';
$labels['sync'] = 'Synchroniseer CardDAVs';
$labels['add'] = 'Toevoegen';
$labels['server_url'] = 'CardDAV server URL';
$labels['settings_label'] = 'Categorie';
$labels['settings_read_only'] = 'Alleen lezen';
$labels['settings_curl_not_installed'] = 'De PHP extensie CURL is niet geinstalleerd! CURL is nooitzakelijk voor deze plugin. ';
$labels['addressbook_contacts'] = 'CardDAV contactpersonen';
$labels['settings_empty_values'] = 'Alle informatie invullen';
$labels['settings_saved'] = 'CardDAV server instellingen en vCards zijn opgeslagen';
$labels['settings_save_failed'] = 'Kan de CardDAV instellingen niet opslaan';
$labels['settings_delete_loading'] = 'Verwijder de CardDAV server instellingen en gerelateerde local contacten';
$labels['settings_deleted'] = 'CardDAV server instellingen verwijderd';
$labels['settings_delete_failed'] = 'Kan de CardDAV server instellingen niet verwijderen';
$labels['settings_no_connection'] = 'Krijg geen verbinding met een CardDAV server';
$labels['settings_init_server'] = 'Controleren van de CardDAV server verbinding en importeer vCards';
$labels['addressbook_synced'] = 'CardDAV contactpersonen gesynchroniseerd';
$labels['addressbook_sync_failed'] = 'Er is een probleem ontstaan tijdens het synschroniseren van de CardDAV contacten';
$labels['addressbook_sync_loading'] = 'Synchroniseer CardDAV contactpersonen';
$labels['contact_moved_single'] = 'Contact met succes verplaatst';
$labels['contact_moved_multiple'] = 'Contactpersonen met succes verplaatst';
$labels['autocomplete'] = 'Automatisch aanvullen';
$labels['automaticallycollected'] = 'Automatisch verzameld';
$labels['automaticallycollected_local'] = 'Automatisch verzameld (lokaal)';
$labels['useautoabook'] = 'Gebruik automatisch adresboek';
$labels['useforcompletion'] = 'Gebruik automatisch verzamelde adressen voor auto aanvullen';
$labels['automatic_addressbook'] = 'Verzamelde contacten automatisch toevoegen aan..';
$labels['googlecontacts'] = 'Google contactpersonen';
$labels['usegoogleabook'] = 'Gebruik het adressenboek van Google';
$labels['googleuser'] = 'Google gebruikernaam';
$labels['googlepass'] = 'Google wachtwoord';
$labels['googlepassisset'] = 'Google wachtwoord is aanwezig';
$labels['googlepassisnotset'] = 'Google wachtwoord is niet aanwezig';
$labels['toggle'] = 'wissellen';
$labels['protected'] = 'Afgeschermd';
$labels['defaultaddressbook'] = 'Persoonlijke contacten';
$labels['Google'] = 'Google';
$labels['Global'] = 'Globaal (alleen lezen)';
$labels['Work'] = 'Werk';
$labels['Family'] = 'Familie';
$labels['Personal'] = 'Persoonlijk';
$labels['Collected'] = 'Verzameld';
$labels['local'] = 'lokaal';
$labels['fe'] = 'b.v.';
$labels['googlecaptcha'] = 'Geef toestemming om je Google Account te gebruiken';
$labels['clickhere'] = 'Hier klikken';
$labels['blank'] = 'leeg';

?>