<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/pt_BR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: filhocf - 07/19/2012 15:04:57
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['settings'] = 'Configurações de CardDAV';
$labels['settings_server'] = 'Servidor de CardDAV';
$labels['settings_server_form'] = 'Adicionar seu servidor de CardDAV';
$labels['settings_example_server_list'] = 'URLs de exemplo de servidor CardDAV';
$labels['settings_tab'] = 'CardDAV';
$labels['settings_label'] = 'Etiqueta';
$labels['settings_read_only'] = 'Somente leitura';
$labels['settings_curl_not_installed'] = 'A extensão CURL do PHP não está instalado! Por favor, instale o CURL para usar o plugin CardDAV.';
$labels['addressbook_contacts'] = 'Contatos CardDAV';
$labels['addressbook_sync'] = 'Sincronizar o catálogo CardDAV';
$labels['settings_empty_values'] = 'Por favor, preencha todas as etiquetas e URL';
$labels['settings_saved'] = 'Configurações do servidor CardDAV e vCards salvos';
$labels['settings_save_failed'] = 'Salvar as configurações do servidor CardDAV falhou';
$labels['settings_delete_loading'] = 'Excluir as configurações do servidor CardDAV e contatos locais relacionados';
$labels['settings_deleted'] = 'Configurações do servidor CardDAV excluído';
$labels['settings_delete_failed'] = 'Exclusão das configurações do servidor CardDAV falhou';
$labels['settings_no_connection'] = 'Não foi possível conectar no servidor CardDAV';
$labels['settings_init_server'] = 'Verificando a conexão ao servidor CardDAV e importação dos vCards';
$labels['addressbook_synced'] = 'Contatos CardDAV sincronizados';
$labels['addressbook_sync_failed'] = 'Um erro ocorreu enquanto sincronizava os contatos CardDAV';
$labels['addressbook_sync_loading'] = 'Sincronizar os contatos CardDAV';

?>