<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/carddav/localization/ru_RU.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: Pavel - 02/11/2013 18:09:35
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'CardDAV';
$labels['plugindescription'] = 'Управление вашими контактами на сервере CardDAV';
$labels['settings'] = 'Установки CardDAV';
$labels['sharing'] = 'Поделиться';
$labels['resource'] = 'Источник';
$labels['confidentialcarddavaccess'] = 'Доступ к [%s] закрыт';
$labels['sharehint'] = 'Предоставьте следующую информацию (Имя пользователя, Пароль (ключ), и URL) для других пользователей для подсоединения к вашим адресным книгам, которыми вы хотите с ними поделиться. Доступ будет дан как на чтение так и на запись. Измените пароль или уберите ключ для закрытия доступа';
$labels['sharehint_readonly'] = 'Предоставьте следующую информацию (Имя пользователя, Пароль (ключ), и URL) для других пользователей для подсоединения к вашим адресным книгам, которыми вы хотите с ними поделиться. Доступ будет дан ТОЛЬКО на чтение. Измените пароль или уберите ключ для закрытия доступа';
$labels['readwrite'] = 'чтение/запись';
$labels['readonly'] = 'только для чтения';
$labels['abooktoken'] = 'Ключ';
$labels['isenabled'] = 'включен';
$labels['isdisabled'] = 'выключен';
$labels['sync_short'] = 'Синхронизировать';
$labels['sync'] = 'Синхронизировать CardDAV';
$labels['add'] = 'Добавить';
$labels['server_url'] = 'URL сервера CardDAV';
$labels['settings_label'] = 'Категория';
$labels['settings_read_only'] = 'Только для чтения';
$labels['settings_curl_not_installed'] = 'Расширение PHP CURL не установлено! Установите CURL для использования плагина CardDAV';
$labels['addressbook_contacts'] = 'Контакты CardDAV';
$labels['settings_empty_values'] = 'Пожалуйста заполните все поля и URL';
$labels['settings_saved'] = 'Установки сервера CardDAV и карточки контактов сохранены';
$labels['settings_save_failed'] = 'Ошибка при сохранении установок сервера CardDAV';
$labels['settings_delete_loading'] = 'Удалить настройки сервера CardDAV и соответствующие локальные контакты';
$labels['settings_deleted'] = 'Настройки сервера CardDAV удалены';
$labels['settings_delete_failed'] = 'Ошибка при удалении установок сервера CardDAV';
$labels['settings_no_connection'] = 'Невозможно связаться с сервером CardDAV';
$labels['settings_init_server'] = 'Проверить связь с сервером CardDAV и импортировать контакты';
$labels['addressbook_synced'] = 'Контакты CardDAV синхронизированы';
$labels['addressbook_sync_failed'] = 'Ошибка при синхронизации контактов CardDAV';
$labels['addressbook_sync_loading'] = 'Синхронизация контактов CardDAV';
$labels['contact_moved_single'] = 'Контакт успешно перемещен';
$labels['contact_moved_multiple'] = 'Контакты успешно перемещены';
$labels['autocomplete'] = 'Автозавершение';
$labels['automaticallycollected'] = 'Собранные адреса';
$labels['automaticallycollected_local'] = 'Автоматический сбор';
$labels['useautoabook'] = 'Использовать собранные адреса';
$labels['useforcompletion'] = 'Использовать автоматически собранные адреса для автозавершения';
$labels['automatic_addressbook'] = 'Добавить автоматически собранные контакты в...';
$labels['googlecontacts'] = 'Контакты Google';
$labels['usegoogleabook'] = 'Использовать адресную книгу Google';
$labels['googleuser'] = 'Аккаунт Google';
$labels['googlepass'] = 'Пароль Google';
$labels['googlepassisset'] = 'Пароль Google введен';
$labels['googlepassisnotset'] = 'Пароль Google еще не введен';
$labels['defaultaddressbook'] = 'Личные Контакты';
$labels['Google'] = 'Google';
$labels['Work'] = 'Рабочий';
$labels['Family'] = 'Семья';
$labels['Personal'] = 'Личный';
$labels['googlecaptcha'] = 'Необходимо передать доступ к вашему аккаунтe Google';
$labels['clickhere'] = 'Нажмите здесь';
$labels['blank'] = ' ';

?>