<?php

/*
+-----------------------------------------------------------------------+
| language/zh_TW/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: ysliuthomas                                                   |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['automaticallycollected'] = '自動蒐集通訊錄';
$labels['useautoabook'] = '啟用自動蒐集通訊錄';

?>