<?php
# 
# This file is part of Roundcube "calendar_plus" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Kalender +';
$labels['plugindescription']='Erweiterte Optionen zur Kalender-Erweiterung hinzufügen (CalDAV, erweiterte Druckoptionen, Ereignisse von vcf-Dateien importieren, kleinen Kalender in die Mailboxansicht einbetten, Geburtstage anzeigen, Kalender für andere Benutzer freigeben, Feeds, Ereignisse filtern, Ereignisse suchen).';