<?php
# 
# This file is part of Roundcube "calendar_plus" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Calendario +';
$labels['plugindescription']='Agregar características avanzadas al complemento Calendario (CalDAV, funciones avanzadas de impresión, eventos de importación de vcf, mostrar pequeño calendario en lista de mensajes, fecha de cumpleaños, compartir calendarios, feeds, eventos, búsqueda y filtros de eventos).';