<?php
# 
# This file is part of Roundcube "calendar_plus" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Календарь +';
$labels['plugindescription']='Добавляет расширенный функционал к плагину Календарь (CalDAV, расширенные опции печати, импорт событий из vcf, показывает маленький календарь в списке сообщений, показывает дни рождения, общий доступ к календарям, потоки, фильтр событий, поиск)';