<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/plugin_manager/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:05:31
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['plugin_manager_title'] = 'Erweiterungen verwalten';
$labels['calendaring'] = 'Aufgaben und Termine verwalten';
$labels['misc'] = 'Verschiedenes';
$labels['translate'] = 'Diese Erweiterung übersetzen ';
$labels['restoredefaults'] = 'Grundeinstellung wiederherstellen';
$labels['checkall'] = 'Alle auswählen';
$labels['uncheckall'] = 'Alle abwählen';
$labels['toggle'] = 'Auswahl umkehren';
$labels['status'] = 'Status';
$labels['globalplugins'] = 'Globale Erweiterungen';
$labels['backend'] = 'Server-Erweiterungen';
$labels['messagesmanagement'] = 'Nachrichtenverwaltung';
$labels['furtherconfig'] = 'Diese Erweiterung erfordert weitere Einstellungen. Möchen Sie die Einstellungen jetzt vornehmen?';
$labels['uninstall'] = 'Möchten Sie alle gespeicherten Einstellungen löschen?';
$labels['uninstallconfirm'] = 'Möchten Sie Ihre persönlichen Einstellungen dieser Erweiterung behalten oder entfernen? Wenn Si...';
$labels['areyousure'] = 'Sie können diese Aktion nicht rückgängig machen. Sind Sie wirklich sicher?';
$labels['successfullydeleted'] = 'Einstellungen wurden erfolgreich entfernt.';
$labels['successfullysaved'] = 'Erfolgreich gespeichert.';
$labels['errorsaving'] = 'Beim Speichern ist ein Fehler aufgetreten.';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nein';
$labels['disable'] = 'Behalten';
$labels['remove'] = 'Entfernen';
$labels['savewarning'] = 'Möchten Sie Ihre Änderungen jetzt speichern?';
$labels['plugin_manager_update'] = 'Erweiterungen erneuern';
$labels['authors_comments'] = 'Anmerkungen des Autors (nicht übersetzt)';
$labels['requiredby'] = 'Erweiterung wird benötigt von';
$labels['requires'] = 'Benötigte Erweiterung(en)';
$labels['recommended'] = 'Empfohlene Erweiterung(en)';
$labels['update_plugins'] = 'Nach Updates suchen';
$labels['ziparchive'] = 'Zip-Archiv herunterladen';
$labels['serverversion'] = 'Server-Version';
$labels['mirrorversion'] = 'Mirror-Version';
$labels['mirrorhost'] = 'Mirror-Server';
$labels['comments'] = 'Voraussetzungen und Amerkungen';
$labels['update_error'] = 'Versionskonflikt';
$labels['update_ok'] = 'Die Erweiterung ist aktuell. Es ist kein Update erforderlich.';
$labels['update_edit'] = 'Die Erweiterung muss neu konfiguriert werden und/oder es sind Datenbankanpassungen vorzunehmen. B...';
$labels['servernewer'] = 'Die registrierte Version der Erweiterung ist neuer als die des Mirror-Servers.';
$labels['orhigher'] = 'oder höher';
$labels['rc_ok'] = 'Roundcube Core ist aktuell.';
$labels['update_update'] = 'Die Erweiterung ist veraltet. Bitte erneuern Sie die Erweiterung unter Berücksichtigung der nebe...';
$labels['noupdates'] = 'Es wurden keine Updates ausgewählt.';
$labels['rc_update'] = 'Roundcube Core veraltet. Bitte erneuern Sie Roundcube Core!';
$labels['rc_uptodate'] = 'Roundcube Core ist aktuell.';
$labels['rc_newer'] = 'Roundcube Core ist neuer als die Mirror-Version!';
$labels['nottested'] = 'Bitte benutzen Sie die Erweiterungen mit Vorsicht! Möglicherweise arbeiten die Erweiterungen mit...';
$labels['justunzip'] = 'Entpacken Sie das Archiv über die bestehende Installation.';
$labels['guide'] = 'Anleitung';
$labels['thirdparty'] = 'Das ist keine MyRoundcube-Erweiterung.';
$labels['thirdpartywarning'] = 'Das ist keine MyRoundcube-Erweiterung. Damit Sie die aktuellste Version erhalten und eventuelle H...';
$labels['develsite'] = 'Herunterladen';
$labels['notinstalled'] = 'nicht installiert';
$labels['notregistered'] = 'nicht registriert';
$labels['roundcubeurl'] = 'Roundcube herunterladen';
$labels['languageupdate'] = 'Übsetzungen wurden überarbeitet.';
$labels['donotregister'] = 'Diese Erweiterung braucht nicht registriert zu werden. Sie wird automatisch geladen.';
$labels['register'] = 'Registrieren Sie diese Erweiterung in ./config/main.inc.php <small>[$rcmail_config[\'plugins\'] = a...</small>';
$labels['noplugindescription'] = 'Es konnte keine Beschreibung der Erweiterung gefunden werden.';
$labels['markbuttons_pluginname'] = 'Nachrichten markieren';
$labels['markbuttons_plugindescription'] = 'Ein Menue zum gleichzeitigen markieren mehrer Nachrichten hinzufügen.';
$labels['chbox_pluginname'] = 'Checkboxen in der Nachrichtenliste';
$labels['chbox_plugindescription'] = 'Eine Checkbox zu jeder Nachricht in der Nachrichtenlist hinzufügen.';
$labels['automatic_addressbook_pluginname'] = 'Empfängeradressen sammeln';
$labels['automatic_addressbook_plugindescription'] = 'Die Adressen von ausgehenden Nachrichten in einem separaten Adressbuch sammeln.';
$labels['keyboard_shortcuts_pluginname'] = 'Tastatureingaben';
$labels['keyboard_shortcuts_plugindescription'] = 'Die Webmail-Oberfläche über Tastaturbefehle steuern.';
$labels['message_highlight_pluginname'] = 'Nachrichtenhervorhebung';
$labels['message_highlight_plugindescription'] = 'Nachrichten in der Nachrichtenliste nach bestimmten Filterkriterien hervorheben.';
$labels['tinymce_pluginname'] = 'Virtuelle Tastatur';
$labels['tinymce_plugindescription'] = 'Fügen Sie eine virtuelle Tastatur zum HTML-Editor hinzu.';
$labels['fixTHEAD_pluginname'] = 'Tabellenkopf fixieren';
$labels['fixTHEAD_plugindescription'] = 'Fixieren Sie den Tabellenkopf der Nachrichtenliste.';
$labels['compose_addressbook_pluginname'] = 'Adressbuchzugriff';
$labels['compose_addressbook_plugindescription'] = 'Sie wollen in Ihren Adressbücher nachsehen, wenn Sie Nachrichten erstellen? Dann aktivieren Sie ...';
$labels['google_contacts_pluginname'] = 'Google-Adressen';
$labels['google_contacts_plugindescription'] = 'Machen Sie Ihre Google-Kontakte verfügbar.';
$labels['contextmenu_pluginname'] = 'Rechter Mausklick';
$labels['contextmenu_plugindescription'] = 'Erledigen Sie viele Sachen einfach mit einem rechten Mausklick.';
$labels['newmail_notifier_pluginname'] = 'Benachrichtigung bei neuen Nachrichten';
$labels['newmail_notifier_plugindescription'] = 'Benachrichtigung bei neuen Nachrichten anzeigen.';
$labels['listcommands_pluginname'] = 'Beantwortung von Mailing-Lists';
$labels['listcommands_plugindescription'] = 'Verschiedene Optionen zur Beantwortung von Nachrichten, die an eine Mailing-List versandt werden.';
$labels['copymessage_pluginname'] = 'Nachrichten kopieren';
$labels['copymessage_plugindescription'] = 'Eine oder mehrer Nachrichten in einen anderen IMAP-Ordner kopieren.';
$labels['forwardattachment_pluginname'] = 'Nachrichten als Anhang weiterleiten';
$labels['forwardattachment_plugindescription'] = 'Leiten Sie mehrere Nachrichten gleichzeitig als Anhang weiter.';
$labels['vcard_attachments_pluginname'] = 'vCard-Anhänge';
$labels['vcard_attachments_plugindescription'] = 'vCard-Anhänge direkt in das Adressbuch importieren.';
$labels['importmessages_pluginname'] = 'Nachrichten importieren';
$labels['importmessages_plugindescription'] = 'Nachrichten von einer eml- oder zip-Quelle importieren.';
$labels['zipdownload_pluginname'] = 'Nachrichten exportieren';
$labels['zipdownload_plugindescription'] = 'Nachrichten als zip-Datei exportieren.';
$labels['markasjunk2_pluginname'] = 'Nachrichten als Spam kennzeichnen';
$labels['markasjunk2_plugindescription'] = 'Nachrichten als Spam kennzeichnen oder die Spamkennzeichnung von legitimen Nachrichten entfernen.';
$labels['google_ads_pluginname'] = 'Google Ads';
$labels['google_ads_plugindescription'] = 'Google Werbung anzeigen.';
$labels['google_analytics_pluginname'] = 'Google Analytics';
$labels['google_analytics_plugindescription'] = 'Google Analytics erlauben.';
$labels['fileapi_attachments_pluginname'] = 'Anhänge per Drag &amp; Drop';
$labels['fileapi_attachments_plugindescription'] = 'Dateien per Drag &amp; Drop anhängen.';
$labels['globaladdressbook_pluginname'] = 'Globales Adressbuch';
$labels['globaladdressbook_plugindescription'] = 'Dieses Adressbuch enthält Adressen, die von Ihrem  Administrator zur Verfügung gestellt werden.';
$labels['blockspamsending_pluginname'] = 'Spamversand vermeiden';
$labels['blockspamsending_plugindescription'] = 'Limitieren Sie den Versand von Nachrichrichten gleichen Inhalts während einer Sitzung.';
$labels['global_config_pluginname'] = 'Konfigurations-Manager';
$labels['global_config_plugindescription'] = 'Optimieren Sie die Performance Ihres Servers durch Zusammenfassung der einzelnen Erweiterungskonf...';
$labels['jqueryui_pluginname'] = 'Jqueryui';
$labels['jqueryui_plugindescription'] = 'Jqueryui Javascript-Bibliothek';

?>