<?php

/*
+-----------------------------------------------------------------------+
| language/el_GR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['pluginname'] = 'Διαχειριστής Προσθέτων';
$labels['plugin_manager_title'] = 'Διαχείριση Προσθέτων';
$labels['misc'] = 'Διάφορα';
$labels['downloads'] = 'μεταφορτώσεις';
$labels['showall'] = 'Προβολή όλων των Προσθέτων';
$labels['hideuptodate'] = 'Προβολή μόνο αναβαθμίσεων';
$labels['trylater'] = 'Παρακαλώ προσπαθήστε αργότερα...';
$labels['translate'] = 'Μεταφράστε αυτό το Πρόσθετο';
$labels['restoredefaults'] = 'Επαναφορά Προεπιλογών';
$labels['checkall'] = 'Επιλογή Όλων';
$labels['uncheckall'] = 'Αποεπιλογή Όλων';
$labels['status'] = 'Κατάσταση';
$labels['backend'] = 'Πρόσθετα Διακομιστή';
$labels['messagesmanagement'] = 'Διαχείριση Μηνυμάτων';
$labels['furtherconfig'] = 'Θέλετε να ρυθμίσετε αυτό το πρόσθετο τώρα?';
$labels['uninstall'] = 'Πρόκειται να απενεργοποιήσετε αυτό το πρόσθετο. Θέλετε να αφαιρέσετε όλες τις αποθηκευμένες ρυθμίσεις μόνιμα;';
$labels['successfullydeleted'] = 'Οι ρυθμίσεις αφαιρέθηκαν επιτυχώς.';
$labels['successfullysaved'] = 'Αποθηκεύτηκε επιτυχώς.';
$labels['errorsaving'] = 'Προέκυψε σφάλμα κατά την αποθήκευση.';
$labels['yes'] = 'Ναι';
$labels['no'] = 'Όχι';
$labels['disable'] = 'Απενεργοποίηση';
$labels['remove'] = 'Αφαίρεση';
$labels['plugin_manager_update'] = 'Αναβάθμιση Προσθέτων';
$labels['recommended'] = 'Προτεινόμενα Πρόσθετα';
$labels['serverversion'] = 'Έκδοση Διακομιστή';
$labels['orhigher'] = 'ή μεγαλύτερο';
$labels['noupdates'] = 'Δεν επιλέχθηκαν Ενημερώσεις.';
$labels['guide'] = 'Διαβάστε περισσότερα...';
$labels['thirdparty'] = 'Αυτό δεν είναι πρόσθετο του MyRoundcube.';
$labels['notinstalled'] = 'μη εγκατεστημένο';
$labels['customer_account'] = 'Λογαριασμός Πελάτη';
$labels['history'] = 'Ιστορικό Λογαριασμού';
$labels['details'] = 'Λεπτομέρειες';
$labels['receipt'] = 'Απόδειξη';
$labels['plugins'] = 'Πρόσθετα';
$labels['sum'] = 'Σύνολο';
$labels['show'] = 'Προβολή';
$labels['hide'] = 'Απόκρυψη';
$labels['view'] = 'προβολή';
$labels['terms'] = 'Όροι';
$labels['codeimprovements'] = 'Βελτιώσεις κώδικα';
$labels['printcompress'] = 'Εκτύπωση και συμπίεση λεπτομερειών λογαριασμού';
$labels['google_contacts_pluginname'] = 'Επαφές Google';
$labels['newmail_notifier_plugindescription'] = 'Ειδοποίηση σε νέα μηνύματα.';
$labels['forwardattachment_pluginname'] = 'Προώθηση σαν επισύναψη';
$labels['forwardattachment_plugindescription'] = 'Προώθηση πολλαπλών μηνυμάτων σαν επισυνάψεις.';
$labels['importmessages_pluginname'] = 'Εισαγωγή Μηνυμάτων';
$labels['importmessages_plugindescription'] = 'Εισαγωγή μηνυματων από αρχείο zip ή πηγή eml.';
$labels['zipdownload_pluginname'] = 'Εξαγωγή Μηνυμάτων';
$labels['markasjunk2_pluginname'] = 'Σημείωση Μηνυμάτων ως Ανεπιθύμητα';
$labels['google_ads_pluginname'] = 'Διαφημίσεις Google';
$labels['google_analytics_pluginname'] = 'Google Analytics';
$labels['lang_sel_pluginname'] = 'Επιλογή Γλώσσας';
$labels['lang_sel_plugindescription'] = 'Επιλογή γλώσσας στη σελίδα εισόδου.';
$labels['newuser_pluginname'] = 'Νέος Χρήστης';

?>