<?php

/*
+-----------------------------------------------------------------------+
| language/hu_HU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2012, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: www.aspHOSTpage.com                                           |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['plugin_manager_title'] = 'Beépülő modulok kezelése';
$labels['misc'] = 'Egyebek';
$labels['restoredefaults'] = 'Alapbeállítások visszaállítása';
$labels['checkall'] = 'Mindegyik';
$labels['uncheckall'] = 'Semelyik';
$labels['messagesmanagement'] = 'Üzenetkezelés';
$labels['uninstall'] = 'A modul kikapcsolása a hozzá kapcsolodó összes beállítást véglegesen törli. Ennek tudatában is kikapcsolod?';
$labels['yes'] = 'Igen';
$labels['no'] = 'Nem';
$labels['message_highlight_pluginname'] = 'Üzenetek kiemelése';
$labels['message_highlight_plugindescription'] = 'Üzenetek kiemelése egy megadott feltétel alapján';
$labels['contextmenu_pluginname'] = 'Környezetérzékeny menü';
$labels['contextmenu_plugindescription'] = 'Környezettől függő, jobb egérgombra felbukkanó menü engedélyezése.';

?>