<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/plugin_manager/localization/pt_PT.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2013, Roland 'rosali' Liebl
 |
 +-----------------------------------------------------------------------+
 | Author: RuiSMoura - 01/25/2013 17:57:49
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['pluginname'] = 'Gestor de Plugins';
$labels['plugin_manager_title'] = 'Gerir Plugins';
$labels['plugin_manager_center'] = 'Gestor de Plugins';
$labels['calendaring'] = 'Elementos de Calendário';
$labels['misc'] = 'Vários';
$labels['downloads'] = 'Transferências';
$labels['issue'] = 'problema';
$labels['showall'] = 'Mostrar todos os Plugins';
$labels['hideuptodate'] = 'Mostrar apenas actualizações';
$labels['connectionerror'] = 'O servidor não respondeu à tentativa de ligação.';
$labels['trylater'] = 'Por favor tente mais tarde...';
$labels['translate'] = 'Traduzir Plugin';
$labels['restoredefaults'] = 'Restaurar Definições';
$labels['checkall'] = 'Selecionar Todos';
$labels['uncheckall'] = 'Desmarcar Todos';
$labels['toggle'] = 'Inverter Seleção';
$labels['status'] = 'Estado';
$labels['globalplugins'] = 'Plugins Globais';
$labels['backend'] = 'Plugins do Servidor';
$labels['messagesmanagement'] = 'Gestão de Mensagens';
$labels['furtherconfig'] = 'Quer configurar este plugin agora?';
$labels['uninstall'] = 'Este plugin será desativado. Quer remover definitivamente todas as definições gravadas?';
$labels['areyousure'] = 'Não pode desfazer esta ação. Tem a certeza?';
$labels['successfullydeleted'] = 'As definições foram removidas com sucesso.';
$labels['successfullysaved'] = 'Gravado com sucesso.';
$labels['errorsaving'] = 'Ocorreu um erro ao gravar.';
$labels['yes'] = 'Sim';
$labels['no'] = 'Não';
$labels['disable'] = 'Desativar';
$labels['remove'] = 'Remover';
$labels['savewarning'] = 'Pertende gravar as suas alterações já?';
$labels['plugin_manager_update'] = 'Atualizar Plugins';
$labels['authors_comments'] = 'Comentários do Autor (não traduzido)';
$labels['requiredby'] = 'O plugin é requerido pelo';
$labels['requires'] = 'O plugin requer';
$labels['recommended'] = 'Plugins recomendados';
$labels['update_plugins'] = 'Transferir Plugins';
$labels['ziparchive'] = 'Transferir Arquivo-Zip ';
$labels['demoaccount'] = 'Desculpe, download desactivado (Conta de Demonstração)';
$labels['serverversion'] = 'Versão no Servidor';
$labels['mirrorversion'] = 'Versão no Servidor-Espelho';
$labels['mirrorhost'] = 'Servidor-Espelho';
$labels['comments'] = 'Requisitos e Notas de Atualização';
$labels['update_error'] = 'Versão não coincide';
$labels['update_ok'] = 'Versão mais actual detetada, Não é necessária atualização';
$labels['update_edit'] = 'O Plugin precisa de ser reconfigurado ou requer ajustes na base de dados. Por favor tenha em considerção as Notas de Actualização ';
$labels['servernewer'] = 'O Plugin é mais recente do que o da versão do servidor-espelho.';
$labels['orhigher'] = 'ou superior';
$labels['rc_ok'] = 'O Roundcube está atualizado.';
$labels['update_update'] = 'Plugin desatualizado. Por favor atualize! Tenha em Consideração as Notas de Atualização.';
$labels['noupdates'] = 'Nenhuma atualização detetada.';
$labels['rc_update'] = 'O Roundcube está desatualizado. Por favor atualize!';
$labels['rc_uptodate'] = 'O Roundcube está atualizado.';
$labels['nottested'] = 'Por favor use os Plugins com precaução! Não sabemos se os Plugins alojados funcionam com o Roundcube  v%s.';
$labels['justunzip'] = 'Apenas descompacte o arquivo para a instalação existente.';
$labels['guide'] = 'Leia mais...';
$labels['thirdparty'] = 'Isto não é um Plugin do MyRoundcube';
$labels['thirdpartywarning'] = 'Este é um plugin de terceiros. Recomendamos que não faça o download do nosso servidor. Em vez disso faça o download diretamente do site do autor para assim obter a última versão assim como todas as notas e conselhos do seu autor.';
$labels['develsite'] = 'Transferir';
$labels['notinstalled'] = 'não instalado';
$labels['notregistered'] = 'não registado';
$labels['roundcubeurl'] = 'Transferir o Roundcube ';
$labels['languageupdate'] = 'Está disponível uma atualização de linguagem.';
$labels['noplugindescription'] = 'Nenhuma descrição encontrada para este plugin.';
$labels['markbuttons_pluginname'] = 'Botões para Sinalização de Mensagens';
$labels['markbuttons_plugindescription'] = 'Acrescenta icons sob a lista de mensagens para rapidamente sinalizar mensagens.';
$labels['automatic_addressbook_pluginname'] = 'Livro de endereços Automático';
$labels['automatic_addressbook_plugindescription'] = 'Captar endereços de email não existentes para um livro de endereços em separado.';
$labels['keyboard_shortcuts_pluginname'] = 'Atalhos de teclado';
$labels['message_highlight_pluginname'] = 'Destacar Mensagens';
$labels['message_highlight_plugindescription'] = 'Destacar mensagens de acordo com as opções de filtro.';
$labels['compose_addressbook_pluginname'] = 'Livro de Endereços na Janela de Composição.';
$labels['google_contacts_pluginname'] = 'Contactos Google';
$labels['google_contacts_plugindescription'] = 'Tenha acesso aos seus contactos do Google.';
$labels['contextmenu_pluginname'] = 'Menu de Contexto';
$labels['contextmenu_plugindescription'] = 'Activar a funcionalidade menu de contexto.';
$labels['newmail_notifier_pluginname'] = 'Novo Notificador de Email';
$labels['newmail_notifier_plugindescription'] = 'Receba um alterta de nova mensagem.';
$labels['copymessage_pluginname'] = 'Copiar Mensagem(s)';
$labels['copymessage_plugindescription'] = 'Copia mensagem(s) para outra pasta IMAP.';
$labels['forwardattachment_pluginname'] = 'Reencaminhar como anexo';
$labels['forwardattachment_plugindescription'] = 'Reencaminha várias mensagens como anexos.';
$labels['vcard_attachments_pluginname'] = 'Anexos vCard';
$labels['vcard_attachments_plugindescription'] = 'Adiciona uma caixa às mensagens que tenham em anexo um vcard, para importar diretamente para o livro de endereços.';
$labels['importmessages_pluginname'] = 'Importar Mensagens';
$labels['importmessages_plugindescription'] = 'Importa mensagens de uma fonte zip ou eml.';
$labels['zipdownload_pluginname'] = 'Exportar Mensagens';
$labels['zipdownload_plugindescription'] = 'Exportar mensagens num ficheiro zip.';
$labels['markasjunk2_pluginname'] = 'Marcar Mensagem como Spam';
$labels['markasjunk2_plugindescription'] = 'Marca as Mensagens como sendo spam ou não.';
$labels['google_ads_pluginname'] = 'Anúncios Google';
$labels['google_ads_plugindescription'] = 'Mostra Publicidade do Google.';
$labels['globaladdressbook_pluginname'] = 'Livro de Endereços Global';
$labels['blockspamsending_pluginname'] = 'Previne Enviar Spam';
$labels['impersonate_pluginname'] = 'Personificar';
$labels['impersonate_plugindescription'] = 'Uma ferramenta de administração que permite iniciar sessão nas contas de email dos utilizadores com uma palvra-passe mestre.';
$labels['jscolor_pluginname'] = 'Palete de cores';
$labels['jscolor_plugindescription'] = 'Um plugin de ajuda que mostra uma palete de cores.';

?>