<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['menu']='Меню';
$labels['managefolders']='Управление на папки';
$labels['account']='Администриране на профила';
$labels['classic']='По подразбиране';
$labels['remotefolders']='Специални папки';
$labels['myroundcube']='MyRoundCube';
$labels['skin_preview']='Преглед на изгледа';