<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Settings';
$labels['plugindescription']='This is a helper plugin. It is required of several other plugins (f.e. all hmail_* plugins).';
$labels['menu']='Menu';
$labels['managefolders']='Manage Folders';
$labels['account']='Account Administration';
$labels['classic']='Default';
$labels['larry']='Larry';
$labels['remotefolders']='Special Folders';
$labels['myroundcube']='MyRoundCube';
$labels['skin_preview']='Skin Preview';