<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Configuración';
$labels['plugindescription']='Este es un complemento de ayuda. Es requerido por otros complemento (p.e. todos los complementos hmail_* ).';
$labels['menu']='Menú';
$labels['managefolders']='Administrar carpetas';
$labels['account']='Administrar cuentas';
$labels['classic']='Por defecto';
$labels['remotefolders']='Carpetas especiales';
$labels['myroundcube']='MyRoundCube';
$labels['skin_preview']='Previsualizar tema';