<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Paramètres';
$labels['plugindescription']='Ce plugin est nécessaire pour le bon fonctionnement d\'autres plugin (par exmple tous les hmail* plugins)';
$labels['menu']='Menu';
$labels['managefolders']='Gestion des dossiers';
$labels['account']='Administration du compte';
$labels['classic']='Default';
$labels['remotefolders']='Dossiers spéciaux';
$labels['myroundcube']='MyRoundCube';
$labels['skin_preview']='Prévisualisation de l\'apparence';
$labels['larry']='Larry';