<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['menu']='Menü';
$labels['managefolders']='Mappák kezelése';
$labels['account']='Fiók kezelése';
$labels['classic']='Alapértelmezett';
$labels['remotefolders']='Speciális mappák';
$labels['myroundcube']='MyRoundCube';
$labels['skin_preview']='Téma előnézet';