<?php
# 
# This file is part of Roundcube "settings" plugin.
# 
# Your are not allowed to distribute this file or parts of it.
# 
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# Copyright (c) 2012 - 2013 Roland 'Rosali' Liebl - all rights reserved.
# dev-team [at] myroundcube [dot] com
# http://myroundcube.com
# 

$labels=array();
$labels['pluginname']='Настройки';
$labels['plugindescription']='Это плагин подсказки. Он требует наличия некоторых других плагинов';
$labels['menu']='Меню';
$labels['managefolders']='Управление папками';
$labels['account']='Управление аккаунтом';
$labels['classic']='Настройки по умолчанию';
$labels['remotefolders']='Особые папки';
$labels['myroundcube']='Мой Roundcube';
$labels['skin_preview']='Предпросмотр Скина';
$labels['larry']='Ларри';