/***************************************************************************
 * This file is part of Roundcube "##PLUGIN##" plugin.              
 *                                                                 
 * Your are not allowed to distribute this file or parts of it.    
 *                                                                 
 * This file is distributed in the hope that it will be useful,    
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.          
 *                                                                 
 * Copyright (c) 2012 - ##YEAR## Roland 'Rosali' Liebl - all rights reserved
 * dev-team [at] myroundcube [dot] com
 * http://myroundcube.com
 ***************************************************************************/

function calendar_splitter(){this.init=function(){rcube_event.add_listener({element:document.getElementById("mailviewsplitterv"),event:"mousedown",object:this,method:"onDragStart"})};this.onDragStart=function(){rcube_event.add_listener({element:document,event:"mousemove",object:this,method:"onDrag"});rcube_event.add_listener({element:document,event:"mouseup",object:this,method:"onDragStop"})};this.onDrag=function(){this.adjust_mboxlist_width()};this.onDragStop=function(){this.adjust_mboxlist_width();
rcube_event.remove_listener({element:document,event:"mousemove",object:this,method:"onDrag"});rcube_event.remove_listener({element:document,event:"mouseup",object:this,method:"onDragStop"})};this.adjust_mboxlist_height=function(){var b=-2;-1<rcmail.env.calskin.indexOf("litecube")&&(b=-33);rcmail.env.mboxlistheight||("classic"!=rcmail.env.calskin?("larry"==rcmail.env.calskin&&(b=-45),rcmail.env.mboxlistheight=$("#mailboxlist").parent().parent().height()+b):rcmail.env.mboxlistheight=$("#mailboxlist").parent().height()+
b);var b=rcmail.env.mboxlistheight,c=Math.round(b/4);$("#mailboxlist").parent().height(Math.max(0,b-c-1));this.set_cookie("mailboxlist-height",Math.max(0,b-c-1));$("#upcoming-content").height(Math.max(0,c));$("#calendaroverlay").height(Math.max(0,c));this.set_cookie("upcoming-height",Math.max(0,c))};this.adjust_mboxlist_width=function(){var b=$("#mailboxlist-container").width();b||(b=$("#mailboxcontainer").width());$("#upcoming-content").width(b);$("#calendaroverlay").width(b);$("#upcoming-container").width(b);
this.set_cookie("upcoming-width",b)};this.set_cookie=function(b,c){var a=new Date;a.setYear(a.getFullYear()+1);bw.set_cookie(b,c,a)}}var spl=new calendar_splitter;$(window).load(function(){spl.adjust_mboxlist_height();spl.adjust_mboxlist_width()});$(window).resize(function(){rcmail.env.mboxlistheight=!1;$("#mailboxlist").parent().height($("#mailboxlist-container").height()-44);spl.adjust_mboxlist_height();spl.adjust_mboxlist_width()});
$(window).load(function(){function b(a){rcmail.env.calsettings=a;var b=1E3;rcmail.env.noreplication&&(b=100);"caldav"==a.settings.backend&&window.setTimeout("calendar_replicate.init(rcmail.env.calsettings, 'upcoming');",b);$("#upcoming").fullCalendar({header:{left:"",center:"",right:""},readyState:function(){7<a.settings.cal_previews&&(a.settings.cal_previews=7);for(var d=1;d<a.settings.cal_previews;d++){var b=(new Date($("#upcoming").fullCalendar("getDate").getTime()+864E5*d)).getFullYear(),g=(new Date($("#upcoming").fullCalendar("getDate").getTime()+
864E5*d)).getMonth(),c=(new Date($("#upcoming").fullCalendar("getDate").getTime()+864E5*d)).getDate();$("#upcoming_"+d).fullCalendar("destroy");$("#upcoming_"+d).fullCalendar({header:{left:"",center:"",right:""},titleFormat:{month:a.settings.titleFormatMonth,week:a.settings.titleFormatWeek,day:a.settings.titleFormatDay},columnFormat:{month:a.settings.columnFormatMonth,week:a.settings.columnFormatWeek,day:a.settings.columnFormatDay},theme:a.settings.ui_theme_upcoming,editable:!1,ignoreTimezone:!1,
events:$("#upcoming").fullCalendar("clientEvents"),monthNames:a.settings.months,monthNamesShort:a.settings.months_short,dayNames:a.settings.days,dayNamesShort:a.settings.days_short,firstDay:a.settings.first_day,firstHour:a.settings.first_hour,slotMinutes:60/a.settings.timeslots,timeFormat:js_time_formats[rcmail.env.rc_time_format],axisFormat:js_time_formats[rcmail.env.rc_time_format],defaultView:"basicDay",allDayText:rcmail.gettext("all-day","calendar"),height:1,eventRender:function(d,b,c){b=calendar_common.qtip(d,
b);d.end&&1!=d.allDay?(d=" - "+d.end.format(js_time_formats[rcmail.env.rc_time_format])+" "+d.title,b.find(".fc-event-title").html(d)):calendar_common.modifyEvents(d,b,c,a)},year:b,month:g,date:c})}},titleFormat:{month:a.settings.titleFormatMonth,week:a.settings.titleFormatWeek,day:a.settings.titleFormatDay},columnFormat:{month:a.settings.columnFormatMonth,week:a.settings.columnFormatWeek,day:a.settings.columnFormatDay},theme:a.settings.ui_theme_upcoming,editable:!1,ignoreTimezone:!1,eventSources:calendar_common.eSources(a,
!1),monthNames:a.settings.months,monthNamesShort:a.settings.months_short,dayNames:a.settings.days,dayNamesShort:a.settings.days_short,firstDay:a.settings.first_day,firstHour:a.settings.first_hour,slotMinutes:60/a.settings.timeslots,timeFormat:js_time_formats[rcmail.env.rc_time_format],axisFormat:js_time_formats[rcmail.env.rc_time_format],defaultView:"basicDay",allDayText:rcmail.gettext("all-day","calendar"),height:1,loading:function(a){a?$("#calendaroverlay").show():($("#calendaroverlay").hide(),
$("#upcoming").fullCalendar("removeEvents","preview"),"undefined"!=typeof rcmail.env.myevents&&rcmail.env.myevents[0]&&$("#upcoming").fullCalendar("addEventSource",rcmail.env.myevents))},eventRender:function(d,b,c){b=calendar_common.qtip(d,b);if(d.end&&1!=d.allDay){var e=d.end,c=Math.round(d.start.getTime()/1E3/60),f=Math.round(d.end.getTime()/1E3/60),e=" - "+e.format(js_time_formats[rcmail.env.rc_time_format])+" "+d.title;b.find(".fc-event-title").html(e);if("preview"!=d.id)for(i=c;i<=f;i++)rcmail.env.calendar_occupied[i]=
1;else if(rcmail.env.calendar_occupied[c]||rcmail.env.calendar_occupied[f])d.className=["occupied"],myclass=b.attr("class"),myclass=myclass.replace("preview","occupied"),b.attr("class",myclass)}else calendar_common.modifyEvents(d,b,c,a)},eventAfterRender:function(a,b){if("preview"==a.id){var c=b.css("top");"undefined"!=typeof c&&(c=parseInt(c.replace("px","")),c=Math.max(c,0),$("#upcoming-container").scrollTop(c))}}});$("#upcoming").click(function(){var a=$("#upcoming").fullCalendar("getDate");document.location.href=
"./?_task=dummy&_action=plugin.calendar&_date="+Math.round(a.getTime()/1E3)});if(1<a.settings.cal_previews)for(i=1;i<a.settings.cal_previews;i++)$("#upcoming_"+i).click(function(){var a=$("#"+this.id).fullCalendar("getDate");document.location.href="./?_task=dummy&_action=plugin.calendar&_date="+escape(Math.round(a.getTime()/1E3))});$("#caltoday").click(function(){$("#upcoming").fullCalendar("today");if(1<a.settings.cal_previews)for(i=1;i<a.settings.cal_previews;i++){var b=new Date($("#upcoming").fullCalendar("getDate").getTime()+
864E5*i);$("#upcoming_"+i).fullCalendar("gotoDate",b)}});$("#calback").click(function(){$("#upcoming").fullCalendar("prev");if(1<a.settings.cal_previews)for(i=1;i<a.settings.cal_previews;i++)$("#upcoming_"+i).fullCalendar("prev")});$("#calforward").click(function(){$("#upcoming").fullCalendar("next");if(1<a.settings.cal_previews)for(i=1;i<a.settings.cal_previews;i++)$("#upcoming_"+i).fullCalendar("next")})}if(window.rcmail){rcmail.env.calendar_occupied=[];rcmail.env.calendar_msgid=null;rcmail.env.calendar_response=
null;spl.init();var c=jzTimezoneDetector.determine_timezone();response_text=c.key;response_text="undefined"==typeof c.timezone?"undefined":c.timezone.olson_tz;!rcmail.env.terms&&!parent.summaryisparent&&(rcmail.addEventListener("plugin.getSettings",b),rcmail.http_post("plugin.getSettings","_tzname="+response_text+"&_init=1"))}});