function pm_get_credits(){rcmail.http_post("plugin.plugin_manager_getcredits","")}
function pm_update_credits(b){if(b&&$("#cdlcredits").get(0)&&parseInt(b)&&parseInt(b)!=parseInt($("#cdlcredits").text())){var a=parseInt(b)-parseInt($("#cdlcredits").text()),c=0<a?"green":"red";$("#accountdetails").html();$("#accountdetails > tbody:last").append('<tr><td colspan="4" style="border: 1px solid lightgrey;">MyRC$ '+rcmail.gettext("creditsupdated","plugin_manager")+'</td><td align="right"  style="border: 1px solid lightgrey; color: '+c+';">'+(0<a?"+":"")+a+'</td><td style="border: 1px solid lightgrey;">&nbsp;</td></tr>');
$("#cdlcredits").text(b);rcmail.display_message("MyRC$ "+a+" "+rcmail.gettext("creditsupdated","plugin_manager"),"confirmation")}window.setTimeout("pm_get_credits()",3E4)}function plugin_manager_save_prefs(){$(".mainaction").hide();var b=$('input[name*="man"]').serialize();rcmail.http_post("plugin.plugin_manager_save",b)}
$(document).ready(function(){rcmail.env.framed&&window.setTimeout("pm_get_credits()",1E3);$(".about-link").click(function(){$(".ui-tooltip").hide()});rcmail.addEventListener("init",function(){rcmail.addEventListener("plugin.plugin_manager_getcredits",pm_update_credits)});rcmail.addEventListener("plugin.plugin_manager_success",function(b){rcmail.pm_stat=$('input[name*="man"]').serialize();rcmail.display_message(rcmail.gettext("successfullydeleted","plugin_manager"),"confirmation");b&&eval(b);plugin_manager_save_prefs()});
rcmail.addEventListener("plugin.plugin_manager_saved",function(b){rcmail.pm_stat=$('input[name*="man"]').serialize();rcmail.display_message(rcmail.gettext("successfullysaved","plugin_manager"),"confirmation");b&&eval(b)});rcmail.addEventListener("plugin.plugin_manager_error",function(){rcmail.display_message(rcmail.gettext("errorsaving","plugin_manager"),"error");$(".mainaction").hide();$(":checkbox").each(function(){$(this).prop("disabled",!0)});window.setTimeout("parent.location.href='./?_task=settings&_action=plugin.plugin_manager'",
3E3)});rcmail.addEventListener("init",function(){function b(){rcmail.pm_mh=0;rcmail.pm_mh2=[];rcmail.pm_mw=0;rcmail.pm_top=0;rcmail.pm_row=-1;$(".pm_section").each(function(){$(this).width()>rcmail.pm_mw&&(rcmail.pm_mw=$(this).width());$(this).height()>rcmail.pm_mh&&(rcmail.pm_mh=$(this).height())});$(".pm_section").each(function(){$(this).width(rcmail.pm_mw);$(this).height(rcmail.pm_mh)});$(".pm_fieldset").each(function(){$(this).offset().top>rcmail.pm_top&&(rcmail.pm_row++,rcmail.pm_top=$(this).offset().top,
rcmail.pm_mh2[rcmail.pm_row]||(rcmail.pm_mh2[rcmail.pm_row]=$(this).height()));$(this).height()>rcmail.pm_mh2[rcmail.pm_row]&&(rcmail.pm_mh2[rcmail.pm_row]=$(this).height())});rcmail.pm_top=0;rcmail.pm_row=-1;rcmail.pm_heights=[];rcmail.pm_sections=-1;$(".pm_fieldset").each(function(){$(this).width(rcmail.pm_mw-20);$(this).offset().top>rcmail.pm_top&&(rcmail.pm_row++,rcmail.pm_top=$(this).offset().top);rcmail.pm_sections++;rcmail.pm_heights[rcmail.pm_sections]=rcmail.pm_mh2[rcmail.pm_row];$(this).height(rcmail.pm_mh2[rcmail.pm_row]-
20)});rcmail.pm_sections=-1;$(".pm_section").each(function(){rcmail.pm_sections++;$(this).height(rcmail.pm_heights[rcmail.pm_sections])})}b();$(window).resize(function(){$(".pm_section").each(function(){$(this).attr("style","")});$(".pm_fieldset").each(function(){$(this).attr("style","")});b()});$(".plugin_manager_li").click(function(){$("#pm_restore_defaults").prop("checked",!1);$("#pm_check_all").prop("checked",!1);$("#pm_uncheck_all").prop("checked",!1)});$("#pm_restore_defaults").click(function(){$("#pm_check_all").prop("checked",
!1);$("#pm_uncheck_all").prop("checked",!1);for(var a in rcmail.env.pm_restore)$("#pm_chbox_"+rcmail.env.pm_restore[a][0]).prop("checked",rcmail.env.pm_restore[a][1])});$("#pm_check_all").click(function(){$("#pm_uncheck_all").prop("checked",!1);$("#pm_restore_defaults").prop("checked",!1);for(var a in rcmail.env.pm_restore)$("#pm_chbox_"+rcmail.env.pm_restore[a][0]).prop("checked",!0)});$("#pm_uncheck_all").click(function(){$("#pm_check_all").prop("checked",!1);$("#pm_restore_defaults").prop("checked",
!1);for(var a in rcmail.env.pm_restore)$("#pm_chbox_"+rcmail.env.pm_restore[a][0]).prop("checked",!1)});$("#pm_update_plugins").click(function(){parent.document.location.href="./?_task=settings&_action=plugin.plugin_manager_update&_warning=1"});rcmail.pm_stat=$('input[name*="man"]').serialize();$(".mainaction").hide();$(".mainaction").prop("disabled",!0);$("input:checkbox").click(function(){rcmail.pm_stat!=$('input[name*="man"]').serialize()?($(".mainaction").prop("disabled",!1),$(".mainaction").show()):
($(".mainaction").prop("disabled",!0),$(".mainaction").hide())});$(".fsavedialog").click(function(){var a=$(this).attr("name").replace("_plugin_manager_",""),a=rcmail.gettext(a+".plugindescription");"["!=a.substr(0,1)&&"]"!=a.substr(a.length-1,1)&&!1==$(".mainaction").prop("disabled")&&($(this).prop("checked")&&!$(this).hasClass("fconfig")?plugin_manager_save_prefs():!$(this).hasClass("funinstall")&&(!$(this).hasClass("frequest")&&!$(this).hasClass("frequestforce"))&&plugin_manager_save_prefs())});
$(".fconfig").click(function(){if($(this).prop("checked")){var a=$(this).attr("name").replace("_plugin_manager_",""),c=rcmail.gettext(a+".plugindescription");if("["!=c.substr(0,1)&&"]"!=c.substr(c.length-1,1)&&!1==$(".mainaction").prop("disabled")){$(".mainaction").hide();var b={};b[rcmail.gettext("plugin_manager.yes")]=function(){$("#plugin_manager_config_plugin").val(a);document.forms.form.submit();$("#jqdialog").dialog("close")};b[rcmail.gettext("plugin_manager.no")]=function(){plugin_manager_save_prefs();
$("#jqdialog").dialog("close")};$("#jqdialog").html(c+"<hr /><p>"+rcmail.gettext("plugin_manager.furtherconfig")+"</p>");$("#jqdialog").dialog({title:rcmail.gettext(a+".pluginname"),buttons:b,position:[$(this).offset().left+20,$(this).offset().top+20],zIndex:99999,close:function(){$("#plugin_manager_config_plugin").val("")}})}}else!$(this).hasClass("funinstall")&&(!$(this).hasClass("frequest")&&!$(this).hasClass("frequestforce"))&&plugin_manager_save_prefs()});$(".funinstall").click(function(){if(!$(this).prop("checked")){var a=
$(this).attr("name").replace("_plugin_manager_",""),c=rcmail.gettext(a+".plugindescription");if("["!=c.substr(0,1)&&"]"!=c.substr(c.length-1,1)&&!1==$(".mainaction").prop("disabled")){$(".mainaction").hide();var b={};b[rcmail.gettext("plugin_manager.yes")]=function(){$(".mainaction").prop("disabled",!0);rcmail.http_post("plugin.plugin_manager_uninstall","_uninstall="+a);$("#jqdialog").dialog("close")};b[rcmail.gettext("plugin_manager.no")]=function(){plugin_manager_save_prefs();$("#jqdialog").dialog("close")};
$("#jqdialog").html(c+"<hr /><p>"+rcmail.gettext("plugin_manager.uninstall")+"</p>");$("#jqdialog").dialog({title:rcmail.gettext(a+".pluginname"),buttons:b,position:[$(this).offset().left+20,$(this).offset().top+20],zIndex:99999,close:function(){}})}}});$(".frequest").click(function(){if(!$(this).prop("checked")){$(this).prop("checked",!0);var a=$(this).attr("name").replace("_plugin_manager_",""),c=rcmail.gettext(a+".plugindescription");if("["!=c.substr(0,1)&&"]"!=c.substr(c.length-1,1)&&!1==$(".mainaction").prop("disabled")){$(".mainaction").hide();
var b={};b[rcmail.gettext("plugin_manager.disable")]=function(){$("#pm_chbox_"+a).prop("checked",!1);plugin_manager_save_prefs();$("#jqdialog").dialog("close")};b[rcmail.gettext("plugin_manager.remove")]=function(){$(".mainaction").prop("disabled",!0);$("#pm_chbox_"+a).prop("checked",!1);confirm(rcmail.gettext("plugin_manager.areyousure"))?rcmail.http_post("plugin.plugin_manager_uninstall","_uninstall="+a):plugin_manager_save_prefs();$("#jqdialog").dialog("close")};$("#jqdialog").html(c+"<hr /><p>"+
rcmail.gettext("plugin_manager.uninstallconfirm")+"</p>");$("#jqdialog").dialog({title:rcmail.gettext(a+".pluginname"),buttons:b,position:[$(this).offset().left+20,$(this).offset().top+20],zIndex:99999,close:function(){}})}}});$(".frequestforce").click(function(){if(!$(this).prop("checked")){$(this).prop("checked",!0);var a=$(this).attr("name").replace("_plugin_manager_",""),b=rcmail.gettext(a+".plugindescription");if("["!=b.substr(0,1)&&"]"!=b.substr(b.length-1,1)&&!1==$(".mainaction").prop("disabled")){var d=
{};d[rcmail.gettext("plugin_manager.remove")]=function(){$(".mainaction").prop("disabled",!0);$("#pm_chbox_"+a).prop("checked",!1);rcmail.http_post("plugin.plugin_manager_uninstall","_uninstall="+a);$("#jqdialog").dialog("close")};$("#jqdialog").html(b+"<hr /><p>"+rcmail.gettext("plugin_manager.uninstall")+"</p>");$("#jqdialog").dialog({title:rcmail.gettext(a+".pluginname"),buttons:d,position:[$(this).offset().left+20,$(this).offset().top+20],zIndex:99999,close:function(){}})}}});$(".plugin_manager_ul > li").each(function(){var a=
$(this).attr("id"),a=a.split("pmid_")[1];if(1!=rcmail.env["pm_plugin_"+a]){if(rcmail.env["pm_buttons_"+a])for(var b in rcmail.env["pm_buttons_"+a])parent.$(rcmail.env["pm_buttons_"+a][b]).get(0)?parent.$(rcmail.env["pm_buttons_"+a][b]).hide():parent.$(rcmail.env["pm_buttons_"+a][b]).get(0)&&parent.$(rcmail.env["pm_buttons_"+a][b]).show()}else rcmail.env["pm_buttons_"+a]&&!parent.$(rcmail.env["pm_buttons_"+a][0]).get(0)&&(parent.location.href="./?_task=settings&_action=plugin.plugin_manager");a=rcmail.gettext(a+
".plugindescription");-1==a.indexOf(".plugindescription")&&"["!=a.substr(0,1)&&"]"!=a.substr(a.length-1,1)&&$(this).qtip({content:{title:$(this).text().replace("\n",""),text:a},position:{my:"top left",at:"left bottom",target:$(this),viewport:$(window)},hide:{effect:function(){$(this).slideUp(5,function(){$(this).dequeue()})}},style:{classes:"ui-tooltip-light"}})})})});