function show_caldav_dialog(a,b,c){var d=$("#caldav_dialog");try{if(!0===d.dialog("isOpen"))return}catch(f){}var e={};e[rcmail.gettext("cancel","calendar")]=function(){d.dialog("close");b.checked=!1};e[rcmail.gettext("save","calendar")]=function(){$("#caldav_category").val(a);""!=$("#caldav_user").val()&&""!=$("#caldav_password").val()&&""!=$("#caldav_url").val()?(rcmail.http_post("plugin.calendar_saveCalDAV",$("#caldav_form").serialize()),d.dialog("destroy"),d.hide(),$("#edit_"+c).attr("style","visibility:visible"),
$("#category_handler_"+c).attr("class","protected_category"),$("#dialog_handler_"+c).hide(),$("#category_handler_"+c).attr("onclick","calendar_toggle_caldav(this, '"+a+"')"),$("#category_handler_"+c).attr("title",rcmail.gettext("unlink_caldav","calendar")),b.checked=!1):$("#caldav_user").focus()};e[rcmail.gettext("remove","calendar")]=function(){confirm(rcmail.gettext("unlink_caldav_warning","calendar"))&&(confirm(rcmail.gettext("unlink_events_warning","calendar"))?$("#caldav_remove").val(1):$("#caldav_remove").val(0),
$("#caldav_category").val(a),rcmail.http_post("plugin.calendar_removeCalDAV",$("#caldav_form").serialize()),d.dialog("destroy"),d.hide(),$("#edit_"+c).attr("style","visibility:hidden"),$("#category_handler_"+c).attr("class",""),$("#category_handler_"+c).attr("onclick","removeRow(this.parentNode.parentNode)"),$("#category_handler_"+c).attr("title",rcmail.gettext("remove_category","calendar")),$("#dialog_handler_"+c).show(),b.checked=!1)};d.dialog({modal:!0,width:700,position:"center",title:a,close:function(){d.dialog("destroy");
d.hide();b.checked=!1},buttons:e}).hide()}function calendar_toggle_caldav(a,b,c){"X"==a.value&&(a=document.getElementById("dialog_handler_"+c));rcmail.http_post("plugin.calendar_getCalDAVs","_category="+b);show_caldav_dialog(b,a,c)}
function calendar_getCalDAVs(a){var b=0;$(".edit_caldav").each(function(){"visibility:visible"==$(this).attr("style")&&b++});b>=a.max_caldavs?$("input:radio").each(function(){$(this).attr("disabled",!0)}):$("input:radio").each(function(){$(this).attr("disabled",!1)});calendar_categories_gui(a)}
function calendar_categories_gui(a){$("#caldav_user").val(a.user);"ENCRYPTED"==a.pass||"SESSION"==a.pass||"GOOGLE"==a.pass?($("#caldav_password").val(a.pass),$("#caldav_password").attr("title",rcmail.gettext("passwordisset","calendar"))):($("#caldav_password").val(""),$("#caldav_password").attr("title",rcmail.gettext("passwordisnotset","calendar")));a.url?($("#caldav_url").val(a.url),rcmail.env.caldav_url=a.url):($("#caldav_url").val(a.cat),rcmail.env.caldav_url=a.cat);-1<$("#caldav_url").val().indexOf("google.")?
$("#googlecaptcha").show():$("#googlecaptcha").hide();a.saved?$("#edit_"+a.category_disp).attr("style","visibility:visible"):$("#edit_"+a.category_disp).attr("style","visibility:hidden");a.cal_dont_save_passwords&&($("#caldav_password").attr("readonly",!0),$("#caldav_url").blur(function(){-1<$("#caldav_url").val().indexOf("?access=")&&rcmail.env.caldav_url!=$("#caldav_url").val()&&($("#caldav_password").val(""),$("#caldav_password").attr("title",rcmail.gettext("passwordisnotset","calendar")),$("#caldav_password").attr("readonly",
!1))}));$("#caldav_url").blur(function(){-1<$("#caldav_url").val().indexOf("google.")?$("#googlecaptcha").show():$("#googlecaptcha").hide()});"external"==a.extr||!0===a.extr?$("#caldav_extr").val("external"):$("#caldav_extr").val("internal");"detect"==a.auth?$("#caldav_auth").val("detect"):$("#caldav_auth").val("basic");a.show&&$("#caldav_dialog").show()}
function addRowCategories(a){var b=document.getElementsByTagName("table")[0],c=b.rows.length;a='<input type="text" name="_categories[]" size="'+a+'" />';var d='<input type="button" value="X" onclick="removeRow(this.parentNode.parentNode)" title="'+rcmail.gettext("remove_category","calendar")+'" />';try{var f=b.insertRow(c),e=f.insertCell(0);e.innerHTML="&nbsp;";e.className="title";e=f.insertCell(1);e.innerHTML=d+"&nbsp;"+a+'&nbsp;<input type="text" name="_colors[]" size="6" class="color" value="ffffff" />';
jscolor.init()}catch(g){}jscolor_removeHexStrings()}
function addRowCalFeeds(a){var b=document.getElementsByTagName("table")[0],c=b.rows.length;a='<input type="text" name="_calendarfeeds[]" size="'+a+'" />';var d='<select name="_feedscategories[]">',f;for(f in categories)d+='<option value="'+f+'">'+f+"</option>";d+="</select>";f='<input type="button" value="X" onclick="removeRow(this.parentNode.parentNode)" title="'+rcmail.gettext("remove_feed","calendar")+'" />';try{var e=b.insertRow(c),g=e.insertCell(0);g.innerHTML="&nbsp;";g.className="title";g=
e.insertCell(1);g.innerHTML=f+"&nbsp;"+a+"&nbsp;"+d;jscolor.init()}catch(h){}}function removeRow(a){var b=document.getElementsByTagName("table")[0];try{b.deleteRow(a.rowIndex),document.forms.form.submit()}catch(c){}}
$(document).ready(function(){rcmail.addEventListener("plugin.calendar_getCalDAVs",calendar_getCalDAVs);rcmail.env.form_categories=$(document.forms.form).serialize();$(".color").each(function(){$(this).blur(function(){rcmail.env.form_categories!=$(document.forms.form).serialize()&&$(jscolor.picker.boxB)&&$(jscolor.picker.boxB).mouseleave(function(){document.forms.form.submit()})})})});